"""H2158 Phase 1 -- turn the A/B rows into the committed table + campaign projection.

Reads the rows.json written by h2158_route_ab.py and prints Markdown. Every number is
either MEASURED (came out of an envelope) or MODELLED (computed here from list rates and
a stated token assumption) -- the two are never mixed in one column, because the whole
point of H2158's Phase 1 is to put a measurement in front of a human before anyone
commits to a bill, and "a projection is not a measurement".

The campaign projection is deliberately a RANGE. Its width is dominated by one unknown
(chars-per-token on masked German + Sanskrit + markup), so the range is generated by
sweeping that assumption rather than by quoting a false point estimate.

Offline, reads nothing but rows.json and the manifest. Safe to re-run.

    python src/pilot/h2158_route_ab_report.py --rows pwg_ru/h2158/raw/rows.json

Model: authored by Opus 5 (`claude-opus-5`) for handoff H2158.
"""
import argparse
import json
import os
import statistics
import sys

sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from headless_worker import build_prompt                             # noqa: E402
from parse_workflow_cost import PRICE, cache_write_rate              # noqa: E402

# The campaign target H2152 6.6 states for the remaining bulk lane.
CAMPAIGN_WORDS = 140_000

# Chars-per-token on this corpus is the dominant unknown in any un-measured projection:
# masked German prose with {Tn} placeholders, IAST Sanskrit, and <ls>/<gram> markup all
# tokenize worse than plain English. Sweeping the assumption is honest; picking one is not.
CPT_LOW, CPT_HIGH = 3.0, 4.0


def med(values):
    values = [v for v in values if v is not None]
    return statistics.median(values) if values else None


def summarize(rows, arm):
    sel = [r for r in rows if r['arm'] == arm and not r.get('failure_class')]
    bad = [r for r in rows if r['arm'] == arm and r.get('failure_class')]
    if not sel:
        return None, bad
    return {
        'n': len(sel),
        'wall_ms': med([r['wall_ms'] for r in sel]),
        'create': med([r['usage'].get('cache_creation_input_tokens') for r in sel]),
        'read': med([r['usage'].get('cache_read_input_tokens') for r in sel]),
        'input': med([r['usage'].get('input_tokens') for r in sel]),
        'output': med([r['usage'].get('output_tokens') for r in sel]),
        'cost_1h': med([r['cost_usd_1h_write'] for r in sel]),
        'cost_env': med([r.get('envelope_cost_usd') for r in sel]),
        'first_create': next((r['usage'].get('cache_creation_input_tokens')
                              for r in sel if r['n'] == 1), None),
        'later_read': med([r['usage'].get('cache_read_input_tokens')
                           for r in sel if r['n'] > 1]),
    }, bad


def prompt_shape(manifest, keys):
    """Offline: how much of the real prompt is cacheable vs per-card volatile."""
    out = []
    for key in keys:
        prompt = manifest['prompt']
        nws = prompt.get('nws_rule', '') if manifest['inputs'][key].get('nws') else ''
        prefix = (prompt['preamble'] + prompt.get('grammar', '') + prompt['translation']
                  + ('\n\n' + nws + '\n' if nws else ''))
        whole = build_prompt(manifest, [key])
        words = len((manifest['inputs'][key]['skeleton'] or '').split())
        out.append({'key': key, 'prefix_chars': len(prefix),
                    'tail_chars': len(whole) - len(prefix),
                    'total_chars': len(whole), 'skeleton_words': words})
    return out


def model_api_cost(prefix_chars, tail_chars, out_tokens, cpt, warm):
    """MODELLED per-card API cost. warm=True prices the prefix as a cache READ."""
    pre, tail = prefix_chars / cpt, tail_chars / cpt
    prefix_rate = PRICE['cache_read'] if warm else cache_write_rate('1h')
    return (pre * prefix_rate + tail * PRICE['input']
            + (out_tokens or 0) * PRICE['output']) / 1e6


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    here = os.path.dirname(os.path.abspath(__file__))
    ap.add_argument('--rows', default=os.path.join(
        os.path.dirname(os.path.dirname(here)), 'pwg_ru', 'h2158', 'raw', 'rows.json'))
    ap.add_argument('--manifest', default=os.path.join(here, 'h1209_slice3.manifest.json'))
    args = ap.parse_args()

    with open(args.manifest, encoding='utf-8') as fh:
        manifest = json.load(fh)
    # Shape analysis needs no calls at all, so a missing/failed run must still produce it
    # rather than crashing -- an aborted arm is exactly when you most want the offline half.
    if os.path.exists(args.rows):
        with open(args.rows, encoding='utf-8') as fh:
            data = json.load(fh)
        rows, keys = data['rows'], data['keys']
    else:
        print('_No rows.json at %s — offline shape analysis only._\n' % args.rows)
        rows = []
        keys = list((manifest.get('meta') or {}).get('selected_keys') or [])[:2]

    print('### Prompt shape (offline, exact — no call needed)\n')
    print('| card | cacheable prefix (chars) | volatile card block (chars) | total | '
          'cacheable share | German words |')
    print('|---|---:|---:|---:|---:|---:|')
    shapes = prompt_shape(manifest, keys)
    for s in shapes:
        print('| `%s` | %d | %d | %d | %.0f%% | %d |'
              % (s['key'], s['prefix_chars'], s['tail_chars'], s['total_chars'],
                 100.0 * s['prefix_chars'] / s['total_chars'], s['skeleton_words']))
    tot_chars = sum(s['total_chars'] for s in shapes) / len(shapes)
    tot_words = sum(s['skeleton_words'] for s in shapes) / len(shapes)
    print('\nMean per card: **%.0f prompt chars**, **%.0f German words** '
          '(≈ %.0f–%.0f prompt tokens at %.1f–%.1f chars/token).'
          % (tot_chars, tot_words, tot_chars / CPT_HIGH, tot_chars / CPT_LOW,
             CPT_LOW, CPT_HIGH))

    print('\n### Measured, per arm (median over successful calls)\n')
    print('| arm | n ok | wall clock | cache create | cache read | input | output | '
          '$/call (repriced, 1h write) | $/call (envelope) |')
    print('|---|---:|---:|---:|---:|---:|---:|---:|---:|')
    summaries = {}
    for arm, label in (('cli', 'CLI-headless (production)'), ('api', 'Messages API + cache')):
        s, bad = summarize(rows, arm)
        summaries[arm] = (s, bad)
        if s is None:
            print('| %s | 0 | — | — | — | — | — | — | — |' % label)
            continue
        print('| %s | %d | %.1f s | %s | %s | %s | %s | $%.4f | %s |'
              % (label, s['n'], s['wall_ms'] / 1000.0,
                 s['create'], s['read'], s['input'], s['output'], s['cost_1h'],
                 ('$%.4f' % s['cost_env']) if s['cost_env'] is not None else 'n/a'))

    for arm in ('cli', 'api'):
        s, bad = summaries[arm]
        if bad:
            print('\n**%s failure classes:** %s' % (
                arm, ', '.join(sorted({r['failure_class'] for r in bad}))))
        if s and s['first_create'] is not None and s['later_read'] is not None:
            print('\n**%s cache reuse:** call #1 created %s tokens; later calls read a '
                  'median %s. %s' % (
                      arm, s['first_create'], s['later_read'],
                      'Reuse IS happening.' if (s['later_read'] or 0) > 0
                      else 'NO reuse — every call re-creates its prefix.'))

    cli, _ = summaries['cli']
    api, _ = summaries['api']
    print('\n### Campaign projection — %s words remaining\n' % f'{CAMPAIGN_WORDS:,}')
    cards = CAMPAIGN_WORDS / tot_words if tot_words else None
    print('Assumptions, stated so they can be attacked:')
    print('')
    print('1. Remaining bulk is **%s German words** (H2152 §6.6).' % f'{CAMPAIGN_WORDS:,}')
    print('2. Cards resemble this manifest: **%.0f German words/card** → **≈ %s cards**.'
          % (tot_words, f'{cards:,.0f}' if cards else '?'))
    print('3. One call per card (H2152: HOLD one-card; shape is not the lever).')
    print('4. Sonnet 5 **list** rates ($%.2f in / $%.2f out / $%.2f 1h-write / $%.2f read '
          'per Mtok). The introductory $2/$10 promo is NOT applied — same basis as '
          '`parse_workflow_cost.PRICE`.' % (PRICE['input'], PRICE['output'],
                                            cache_write_rate('1h'), PRICE['cache_read']))
    print('5. Zero retries/heals. Every real campaign has both, so these are **floors**.')
    print('')
    print('| route | basis | $/card | projected campaign |')
    print('|---|---|---:|---|')
    if cli:
        print('| CLI-headless | MEASURED (n=%d) | $%.4f | **$%s** |'
              % (cli['n'], cli['cost_1h'], f'{cli["cost_1h"] * cards:,.0f}'))
    if api:
        print('| Messages API | MEASURED (n=%d) | $%.4f | **$%s** |'
              % (api['n'], api['cost_1h'], f'{api["cost_1h"] * cards:,.0f}'))
    else:
        out_tok = cli['output'] if cli else 2000
        pre = sum(s['prefix_chars'] for s in shapes) / len(shapes)
        tail = sum(s['tail_chars'] for s in shapes) / len(shapes)
        lo = model_api_cost(pre, tail, out_tok, CPT_HIGH, warm=True)
        hi = model_api_cost(pre, tail, out_tok, CPT_LOW, warm=False)
        print('| Messages API | **MODELLED — not measured** | $%.4f–$%.4f | **$%s–$%s** |'
              % (lo, hi, f'{lo * cards:,.0f}', f'{hi * cards:,.0f}'))
        print('')
        print('> The API row is a MODEL, not a result. Low end = warm prefix (cache read) '
              'at %.1f chars/token; high end = cold prefix (1h write) at %.1f chars/token. '
              'It assumes output tokens match the CLI arm\'s measured median (%s). '
              'It cannot close this handoff.' % (CPT_HIGH, CPT_LOW, out_tok))
    return 0


if __name__ == '__main__':
    sys.exit(main())
