#!/usr/bin/env python
"""Article-grade launch-failure statistics harvester for pwg_ru.

The dashboard's `evolution_stats.py` produces day-bucketed TREND series for the
live UI. This script produces the *paper* artifact instead: one tidy per-launch
table (the denominator the narrative doc lacks) with the three disconnected
failure vocabularies reconciled onto it, plus the summary tables a methods /
failure-taxonomy paper needs.

Three registers of "failure" exist in this repo and are NOT the same axis:

  1. window_ledger.jsonl   -> per-window OPERATIONAL state (the population /
                              denominator: every launch, success or not).
  2. LAUNCH_FUCKUPS.md     -> 11-class ORCHESTRATION `classification` taxonomy,
                              hand-curated launch incidents (the numerator).
  3. failures/*.jsonl      -> `mode` CONTENT/CORRECTNESS taxonomy (fabrication,
                              off-by-one, ...) + auto-captured ledger crashes.

This harvester keeps them as explicit separate axes rather than forcing one
vocabulary, and reports each against the window population so a rate is finally
computable.

Usage:
    python src/pilot/harvest_launch_stats.py            # write CSV + JSON + MD
    python src/pilot/harvest_launch_stats.py --stdout   # also print the stats
    python src/pilot/harvest_launch_stats.py --data-root <path>
        # read the (git-ignored, local-only) window ledger + failure logs from a
        # different checkout than the one this script lives in, while still
        # writing outputs next to this script. Used when running from an
        # isolated worktree whose own output/ is empty.

All inputs are best-effort: a missing/partial file degrades that section rather
than raising. Observability must never break on bad data.

Model provenance: authored by Opus 4.8 (`claude-opus-4-8`); the runs it
aggregates were generated by the models each ledger/RUN_LOG row records
(predominantly Sonnet 5 `claude-sonnet-5`, with Fable 5 `claude-fable-5` and
Opus 4.8 orchestration).
"""
import argparse
import collections
import csv
import datetime
import json
import os
import re
import sys

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
# REPO = the checkout this script lives in (outputs are written here).
REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(HERE, 'output')

# Map the ledger's operational `state` to a coarse launch OUTCOME. `needs_requeue`
# is the normal iterative state, NOT a failure — folding it into "failed" is the
# classic denominator error this harvester exists to prevent.
STATE_OUTCOME = {
    'clean': 'clean',
    'partial': 'partial',
    'needs_requeue': 'iterating',
    'stale_artifact': 'stale-refused',
    'blocked': 'crashed',
}
# Genuine hard failures: a launch that produced nothing usable without operator
# intervention beyond an ordinary requeue.
HARD_FAIL_OUTCOMES = {'stale-refused', 'crashed'}


def data_paths(data_root):
    return {
        'ledger': os.path.join(data_root, 'src', 'pilot', 'output', 'window_ledger.jsonl'),
        'fuckups': os.path.join(data_root, 'LAUNCH_FUCKUPS.md'),
        'failures': os.path.join(data_root, 'failures', 'failures.jsonl'),
        'failures_auto': os.path.join(data_root, 'failures', 'auto_failures.jsonl'),
        # H462: the probe log records launches that were REFUSED (abort / NO-GO rows) —
        # structurally invisible to the window ledger, which keys on a launch having happened.
        'probe_log': os.path.join(data_root, 'src', 'pilot', 'generation_api_probe_log.jsonl'),
    }


def iter_jsonl(path):
    if not os.path.exists(path):
        return
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def day_of(ts):
    return ts[:10] if isinstance(ts, str) and len(ts) >= 10 else None


def load_ledger(paths):
    """The population: one row per launched window."""
    rows = []
    for r in iter_jsonl(paths['ledger']):
        state = r.get('state') or 'unknown'
        subcards = r.get('root_subcards') or 0
        translated = r.get('translated') or 0
        wk = r.get('workflow_keys') or 0
        rq = r.get('requeue_count') or 0
        pm = r.get('production_metrics') or {}
        rows.append({
            'date': day_of(r.get('recorded_at')),
            'recorded_at': r.get('recorded_at'),
            'root': r.get('root'),
            'state': state,
            'outcome': STATE_OUTCOME.get(state, 'other'),
            # H390 Phase 1: model that generated the window (None on pre-H390 rows,
            # which the harness never stamped — reported as an explicit coverage gap).
            'gen_model': r.get('gen_model'),
            'workflow_keys': wk,
            'root_subcards': subcards,
            'translated': translated,
            'pending': r.get('pending') or 0,
            'requeue_count': rq,
            'requeue_transient': r.get('requeue_transient_count'),
            'requeue_defect': r.get('requeue_defect_count'),
            'completion_pct': round(100.0 * translated / subcards, 2) if subcards else None,
            'requeue_rate': round(rq / wk, 4) if wk else None,
            'crashed': ';'.join(r.get('crashed') or []),
            'wall_clock_minutes': pm.get('wall_clock_minutes'),
            'max_output_tokens': pm.get('max_output_tokens'),
        })
    return rows


def load_fuckups(paths):
    """The 11-class orchestration incident taxonomy (curated launch failures)."""
    path = paths['fuckups']
    if not os.path.exists(path):
        return []
    txt = open(path, encoding='utf-8').read()
    m = re.search(r'```json launch_failure_ledger\s*(\[.*?\])\s*```', txt, re.S)
    if not m:
        return []
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError:
        return []


def load_content_failures(paths):
    """The `mode` content/correctness register (F-ids) + auto ledger crashes."""
    out = []
    for key, origin in (('failures', 'curated'), ('failures_auto', 'auto')):
        for fr in iter_jsonl(paths[key]):
            out.append({
                'id': fr.get('id'),
                'date': fr.get('date'),
                'mode': fr.get('mode') or 'unknown',
                'severity': fr.get('severity') or 'unknown',
                'source': fr.get('source') or origin,
                'root': fr.get('root'),
                'symptom': (fr.get('symptom') or '')[:160],
            })
    return out


def load_probe_refusals(paths):
    """H462: count probe-log rows that refused/aborted a launch. Kept as a SEPARATE
    denominator, never merged into the window population — mixing refused launches into
    the launched-window rates would silently change the meaning of every existing rate
    (H462 ruling on the open question in the handoff)."""
    aborts = 0
    nogo_warmups = 0
    for r in iter_jsonl(paths.get('probe_log', '')):
        if r.get('kind') == 'abort':
            aborts += 1
        elif r.get('kind') == 'warmup' and r.get('verdict') == 'NO-GO':
            nogo_warmups += 1
    return {'abort_rows': aborts, 'nogo_warmups': nogo_warmups}


def counter_table(rows, key):
    c = collections.Counter(r[key] for r in rows if r.get(key) is not None)
    return sorted(c.items(), key=lambda kv: -kv[1])


def per_model_breakdown(pop):
    """H390 Phase 1: the population sliced by generating model — the axis the
    Fable-vs-Sonnet A/B (Phase 3) reads. Windows with no `gen_model` (pre-H390
    ledger rows the harness never stamped) are bucketed under `(unstamped)` so the
    instrumentation gap is visible, never silently folded into a real model."""
    by = collections.defaultdict(list)
    for r in pop:
        by[r.get('gen_model') or '(unstamped)'].append(r)
    out = []
    for model, rows in sorted(by.items(), key=lambda kv: -len(kv[1])):
        n = len(rows)
        oc = collections.Counter(r['outcome'] for r in rows)
        hard = sum(v for k, v in oc.items() if k in HARD_FAIL_OUTCOMES)
        out.append({
            'gen_model': model,
            'windows': n,
            'clean_windows': oc.get('clean', 0),
            'hard_fail_windows': hard,
            'hard_fail_rate_pct': round(100.0 * hard / n, 2) if n else None,
        })
    return out


def compute(pop, fuckups, content):
    n = len(pop)
    roots = {r['root'] for r in pop if r.get('root')}
    dated = [r['date'] for r in pop if r.get('date')]
    outcome_counts = collections.Counter(r['outcome'] for r in pop)
    hard_fail = sum(v for k, v in outcome_counts.items() if k in HARD_FAIL_OUTCOMES)

    have_minutes = sum(1 for r in pop if r.get('wall_clock_minutes'))
    have_tokens = sum(1 for r in pop if r.get('max_output_tokens'))
    have_model = sum(1 for r in pop if r.get('gen_model'))

    req_rows = [r for r in pop if (r.get('requeue_count') or 0) > 0]
    mean_requeue = (sum(r['requeue_count'] for r in req_rows) / len(req_rows)) if req_rows else 0.0

    return {
        'generated_at': datetime.datetime.now(datetime.timezone.utc)
                        .isoformat(timespec='seconds').replace('+00:00', 'Z'),
        'population': {
            'windows': n,
            'distinct_roots': len(roots),
            'date_span': [min(dated) if dated else None, max(dated) if dated else None],
            'outcome_distribution': dict(outcome_counts),
            'hard_fail_windows': hard_fail,
            'hard_fail_rate_pct': round(100.0 * hard_fail / n, 2) if n else None,
            'windows_that_requeued': len(req_rows),
            'mean_requeues_when_requeued': round(mean_requeue, 2),
            'metric_coverage': {
                'wall_clock_minutes': f'{have_minutes}/{n}',
                'max_output_tokens': f'{have_tokens}/{n}',
                'gen_model': f'{have_model}/{n}',
            },
        },
        'per_model': per_model_breakdown(pop),
        'orchestration_taxonomy': {
            'curated_incidents': len(fuckups),
            'by_classification': counter_table(fuckups, 'classification'),
            'by_residual_status': counter_table(fuckups, 'residual_status'),
            'by_model': counter_table(fuckups, 'model'),
            'by_lane': counter_table(fuckups, 'lane'),
            'incident_rate_per_window_pct':
                round(100.0 * len(fuckups) / n, 2) if n else None,
        },
        'content_taxonomy': {
            'records': len(content),
            'by_mode': counter_table(content, 'mode'),
            'by_severity': counter_table(content, 'severity'),
            'by_source': counter_table(content, 'source'),
        },
        'per_root_windows': sorted(
            collections.Counter(r['root'] for r in pop if r.get('root')).items(),
            key=lambda kv: -kv[1])[:20],
    }


def write_csv(pop):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, 'launch_stats.csv')
    cols = ['date', 'recorded_at', 'root', 'state', 'outcome', 'gen_model',
            'workflow_keys', 'root_subcards', 'translated', 'pending', 'requeue_count',
            'requeue_transient', 'requeue_defect', 'completion_pct',
            'requeue_rate', 'crashed', 'wall_clock_minutes', 'max_output_tokens']
    with open(path, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction='ignore')
        w.writeheader()
        for r in pop:
            w.writerow(r)
    return path


def _md_table(pairs, h1, h2):
    out = [f'| {h1} | {h2} |', '|---|---|']
    out += [f'| `{k}` | {v} |' for k, v in pairs]
    return '\n'.join(out)


def _md_model_table(per_model):
    out = ['| gen_model | windows | clean | hard-fail | hard-fail % |',
           '|---|---:|---:|---:|---:|']
    for m in per_model:
        out.append('| `%s` | %d | %d | %d | %s |' % (
            m['gen_model'], m['windows'], m['clean_windows'],
            m['hard_fail_windows'],
            '—' if m['hard_fail_rate_pct'] is None else m['hard_fail_rate_pct']))
    return '\n'.join(out)


def write_md(stats):
    today = datetime.date.today().strftime('%d-%m-%Y')
    p = stats['population']
    o = stats['orchestration_taxonomy']
    c = stats['content_taxonomy']
    prov = stats.get('provenance') or {}
    refusals = stats.get('probe_refusals') or {}
    lines = [
        '# PWG-RU launch statistics (auto-generated)',
        '',
        f'_Created: 09-07-2026 · Last updated: {today}_',
        '',
        'Auto-generated by [`src/pilot/harvest_launch_stats.py`]'
        '(src/pilot/harvest_launch_stats.py) from the local window ledger, '
        '[`LAUNCH_FUCKUPS.md`](LAUNCH_FUCKUPS.md), and the content-failure gallery. '
        'Do not hand-edit — re-run the harvester. This is the quantitative companion '
        'to the narrative typology in `LAUNCH_FUCKUPS.md`: the denominator and the '
        'rates that turn the typology into an evidence table.',
        '',
        f'Generated: {stats["generated_at"]}',
        '',
        f'**Population source (H462 provenance):** `{prov.get("ledger_rel", "window_ledger.jsonl")}` '
        f'under data-root `{prov.get("data_root", "?")}` — **{prov.get("ledger_rows", "?")}** rows. '
        'The window ledger is local-only (gitignored): a harvest run from a worktree whose '
        'own `output/` holds only that worktree\'s launches silently swaps the denominator '
        '(the 09-07-2026 committed edition reported 3 windows from a worktree ledger while '
        'the main checkout held 450). Always state — and check — this line before citing a rate.',
        '',
        '> **Denominator bias (H462):** every rate below is conditioned on *"we chose to '
        'launch"*. Launches correctly REFUSED by the probe gate never enter the window '
        'ledger, so this file structurally cannot see them: '
        f'**{refusals.get("abort_rows", 0)}** abort row(s) and '
        f'**{refusals.get("nogo_warmups", 0)}** NO-GO warm-up(s) are on record in '
        '[`GENERATION_API_PROBE_LOG.md`](GENERATION_API_PROBE_LOG.md), kept as a separate '
        'denominator by design — merging them would change the meaning of every existing rate.',
        '',
        '## 1. Population (denominator) — every launched window',
        '',
        f'- Windows launched: **{p["windows"]}**  ·  distinct roots: **{p["distinct_roots"]}**',
        f'- Date span: {p["date_span"][0]} → {p["date_span"][1]}',
        f'- Hard-fail windows (stale-refused + crashed): **{p["hard_fail_windows"]}** '
        f'= **{p["hard_fail_rate_pct"]}%**',
        f'- Windows that requeued at least once: **{p["windows_that_requeued"]}** '
        f'(mean **{p["mean_requeues_when_requeued"]}** requeues when they did)',
        '',
        '> Caveat — `needs_requeue` is the *normal* iterative state, not a failure; '
        'folding it into "failed" would be the denominator error this table exists to '
        'avoid. The honest hard-fail rate counts only stale-refused + crashed outcomes.',
        '',
        _md_table([(k, v) for k, v in p['outcome_distribution'].items()],
                  'outcome', 'windows'),
        '',
        f'**Metric coverage (the instrumentation gap the paper must disclose):** '
        f'wall-clock recorded on {p["metric_coverage"]["wall_clock_minutes"]} windows, '
        f'output-tokens on {p["metric_coverage"]["max_output_tokens"]}, '
        f'generating-model on {p["metric_coverage"]["gen_model"]} windows. Per-window '
        'cost/latency must be back-filled from transcript dirs '
        '(`parse_workflow_cost.py`) or captured going forward — it is not yet in the '
        'ledger. Per-window `gen_model` is stamped going forward (H390 Phase 1); rows '
        'generated before that instrumentation carry none and appear under `(unstamped)` '
        'below.',
        '',
        '## 1b. Population by generating model (H390 Phase 1 — the A/B axis)',
        '',
        'The Fable-vs-Sonnet A/B (H390 Phase 3) reads this slice. Until a matched A/B '
        'run exists, expect a single real model plus `(unstamped)` legacy rows — that is '
        'the instrumentation coming online, not a result.',
        '',
        _md_model_table(stats['per_model']),
        '',
        '## 2. Orchestration taxonomy — curated launch incidents',
        '',
        f'- Curated incidents: **{o["curated_incidents"]}**  ·  '
        f'incident rate vs population: **{o["incident_rate_per_window_pct"]}%** '
        'of windows generated a logged incident.',
        '',
        _md_table(o['by_classification'], 'classification', 'incidents'),
        '',
        _md_table(o['by_residual_status'], 'residual status', 'incidents'),
        '',
        _md_table(o['by_model'], 'model', 'incidents'),
        '',
        '## 3. Content/correctness taxonomy — a distinct axis',
        '',
        f'- Records: **{c["records"]}** (curated F-ids + auto-captured). These are '
        'translation/data-correctness failures, NOT launch orchestration — a separate '
        'taxonomy the paper should present as a second axis, not merge into axis 2.',
        '',
        _md_table(c['by_mode'], 'mode', 'records'),
        '',
        _md_table(c['by_severity'], 'severity', 'records'),
        '',
        '## 4. Top roots by window count',
        '',
        _md_table([(k, v) for k, v in stats['per_root_windows']], 'root', 'windows'),
        '',
        '_Auto-generated by `harvest_launch_stats.py` (Opus 4.8 `claude-opus-4-8`)._',
        '',
    ]
    path = os.path.join(REPO, 'LAUNCH_STATS.md')
    open(path, 'w', encoding='utf-8').write('\n'.join(lines))
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data-root', default=REPO,
                    help='checkout to read the local window ledger + failure logs '
                         'from (default: this script\'s own checkout)')
    ap.add_argument('--stdout', action='store_true', help='also print the JSON stats')
    args = ap.parse_args()

    paths = data_paths(os.path.abspath(args.data_root))
    pop = load_ledger(paths)
    fuckups = load_fuckups(paths)
    content = load_content_failures(paths)
    stats = compute(pop, fuckups, content)
    stats['provenance'] = {
        'data_root': os.path.abspath(args.data_root),
        'ledger_rel': os.path.relpath(paths['ledger'], os.path.abspath(args.data_root)),
        'ledger_rows': len(pop),
    }
    stats['probe_refusals'] = load_probe_refusals(paths)

    csv_path = write_csv(pop)
    json_path = os.path.join(OUT, 'launch_stats.json')
    open(json_path, 'w', encoding='utf-8').write(
        json.dumps(stats, ensure_ascii=False, indent=2))
    md_path = write_md(stats)

    print(f'read data from {args.data_root}')
    print(f'wrote {csv_path} ({len(pop)} rows)')
    print(f'wrote {json_path}')
    print(f'wrote {md_path}')
    if args.stdout:
        print(json.dumps(stats, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
