#!/usr/bin/env python
"""build_grounding_levers_report.py — H1670 synthesis.

Reads the per-cell `*.meta.json` written by `pwg_sense_dcs_attestation_pilot.py`
and emits ONE report attributing the PWG-sense × DCS grounding delta to the lever
that produced it. Every number is read from the generated metadata, never
re-typed, so the synthesis cannot drift from the runs it describes.

The cells are a 2×2 over the two INDEPENDENT limits H1670 separated, plus the
Lever-B text-map cell:

                     locus-scan=kwic          locus-scan=full
  frame = 500        baseline (= H1632)       A2 — passage depth alone
  frame = wide       A1 — frame width alone   A1+A2
  frame = wide                                A1+A2+B — plus the text map

Usage:
  python build_grounding_levers_report.py [--dir PATH]
"""
import argparse
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
BLOB = ('https://github.com/gasyoun/SanskritLexicography/blob/master/'
        'RussianTranslation/research')
KOSHA_BLOB = 'https://github.com/gasyoun/kosha/blob/main/scripts'

CELLS = [
    ('baseline', 'pilot', 'H1632 baseline — frozen 500, `--locus-scan kwic`'),
    ('a2', '500full', 'A2 only — frozen 500, `--locus-scan full`'),
    ('a1', 'widekwic', 'A1 only — wide frame, `--locus-scan kwic`'),
    ('a1a2', 'widefull', 'A1+A2 — wide frame, `--locus-scan full`'),
    ('a1a2b', 'widefulltextmap', 'A1+A2+B — wide frame, full scan, + text map'),
]


def load(d, tag):
    p = os.path.join(d, 'pwg_sense_dcs_attestation_%s.meta.json' % tag)
    if not os.path.isfile(p):
        raise SystemExit('missing %s — re-run that cell' % p)
    return json.load(open(p, encoding='utf-8'))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', default=HERE)
    a = ap.parse_args()

    M = {k: load(a.dir, tag) for k, tag, _ in CELLS}
    S = {k: M[k]['summary'] for k in M}
    b, a2, a1, a12, a12b = (S['baseline'], S['a2'], S['a1'], S['a1a2'], S['a1a2b'])
    allm = load(a.dir, 'allh1670')['summary']
    try:
        old_all = json.load(open(os.path.join(
            a.dir, 'pwg_sense_dcs_attestation_all.meta.json'), encoding='utf-8'))['summary']
    except Exception:
        old_all = None

    L = []
    L.append('# PWG-sense × DCS grounding — what actually raised it (H1670)')
    L.append('')
    L.append('_Created: 26-07-2026 · Last updated: 26-07-2026_')
    L.append('')
    L.append('_Auto-generated by `research/build_grounding_levers_report.py` from the '
             'per-cell `*.meta.json` files (H1670, Opus 5 `claude-opus-5[1m]`). Do not '
             'hand-edit the metrics; re-run the cells, then this script._')
    L.append('')
    L.append('## The headline, and the correction it forces')
    L.append('')
    L.append('H1632 measured **%d of %s PWG leaf senses (%.2f%%)** grounded to a DCS '
             'attestation by a shared locus, and concluded that the constraint was data '
             'availability — that scaling "did not and could not raise the grounding '
             'rate", and that growing it "means adding *texts and locus crosswalks*, not '
             'tuning a matcher".'
             % (b['pwg_senses_grounded'], '{:,}'.format(b['pwg_senses_total_known']),
                100 * b['pwg_sense_join_rate']))
    L.append('')
    L.append('**That conclusion was wrong about its own cause.** The aligner was never '
             'data-starved in the way the report supposed. It was *blindfolded*: for each '
             'DCS lemma it compared the sense\'s `<ls>` against only the %d passages that '
             '`dcs_kwic()` had sampled **for the viewer** — 3,435 of the 1,148,630 '
             'passages available under the wave-1 frame, or **0.299%%**. The exact-verse '
             'test was measuring the sample, not the corpus.'
             % M['baseline'].get('kwic_per', 3))
    L.append('')
    L.append('Removing the blindfold — the SAME `verse_equal()` predicate, the same tiers, '
             'no heuristic added — and widening the frame with the SAME selection query '
             'gives:')
    L.append('')
    L.append('| | grounded leaf senses | rate (aligner-covered subset) | of which exact-verse |')
    L.append('|---|---:|---:|---:|')
    for key, _tag, label in CELLS:
        s = S[key]
        L.append('| %s | %s | %.2f%% | %s (%.2f%%) |'
                 % (label, '{:,}'.format(s['pwg_senses_grounded']),
                    100 * s['pwg_sense_join_rate'],
                    '{:,}'.format(s['pwg_senses_grounded_verse']),
                    100 * s['pwg_sense_join_rate_verse']))
    L.append('')
    L.append('**%.1f× the grounded senses (%d → %s) and %.1f× the rate (%.2f%% → %.2f%%), '
             'with no criterion relaxed.**'
             % (a12b['pwg_senses_grounded'] / b['pwg_senses_grounded'],
                b['pwg_senses_grounded'], '{:,}'.format(a12b['pwg_senses_grounded']),
                a12b['pwg_sense_join_rate'] / b['pwg_sense_join_rate'],
                100 * b['pwg_sense_join_rate'], 100 * a12b['pwg_sense_join_rate']))
    L.append('')

    L.append('## Per-lever attribution')
    L.append('')
    L.append('| lever | what changed | grounded senses | Δ vs baseline |')
    L.append('|---|---|---:|---:|')
    L.append('| — | H1632 as published | %d | — |' % b['pwg_senses_grounded'])
    L.append('| **A2 — passage depth** | the locus tiers see every DCS passage at an '
             'address the frame cites, instead of the 3-passage viewer sample | %s | '
             '**+%s (%.1f×)** |'
             % ('{:,}'.format(a2['pwg_senses_grounded']),
                '{:,}'.format(a2['pwg_senses_grounded'] - b['pwg_senses_grounded']),
                a2['pwg_senses_grounded'] / b['pwg_senses_grounded']))
    L.append('| **A1 — frame width** | the same selection query run to exhaustion '
             '(%s groups, %.1f× the frozen 500) instead of truncated at 500 | %s | '
             '**+%s (%.1f×)** |'
             % ('{:,}'.format(a1['n_pilot_groups']), a1['n_pilot_groups'] / 500.0,
                '{:,}'.format(a1['pwg_senses_grounded']),
                '{:,}'.format(a1['pwg_senses_grounded'] - b['pwg_senses_grounded']),
                a1['pwg_senses_grounded'] / b['pwg_senses_grounded']))
    L.append('| A1+A2 | both | %s | +%s |'
             % ('{:,}'.format(a12['pwg_senses_grounded']),
                '{:,}'.format(a12['pwg_senses_grounded'] - b['pwg_senses_grounded'])))
    L.append('| **B — text map** | 5 verified texts added to `PWG_TO_DCS_TEXT`, incl. the '
             'dead `ṚV` key | %s | +%s _(+%s on top of A1+A2)_ |'
             % ('{:,}'.format(a12b['pwg_senses_grounded']),
                '{:,}'.format(a12b['pwg_senses_grounded'] - b['pwg_senses_grounded']),
                '{:,}'.format(a12b['pwg_senses_grounded'] - a12['pwg_senses_grounded'])))
    L.append('')
    L.append('**The levers are strongly super-additive.** A1 alone adds %s grounded '
             'senses and A2 alone adds %s, but together they add %s — far more than the '
             '%s a purely additive model predicts. A wider frame cites more addresses, '
             'and only the full scan can find them; neither lever pays off without the '
             'other.'
             % ('{:,}'.format(a1['pwg_senses_grounded'] - b['pwg_senses_grounded']),
                '{:,}'.format(a2['pwg_senses_grounded'] - b['pwg_senses_grounded']),
                '{:,}'.format(a12['pwg_senses_grounded'] - b['pwg_senses_grounded']),
                '{:,}'.format(a1['pwg_senses_grounded'] + a2['pwg_senses_grounded']
                              - 2 * b['pwg_senses_grounded'])))
    L.append('')
    L.append('⚠️ **A1\'s effect on the *rate* is partly compositional, and must not be '
             'read as "grounding is easier further down the dictionary".** The frozen 500 '
             'were ranked most-polysemous-first, so they carry %.1f leaf senses per group '
             'against the wide frame\'s %.1f. A single grounded locus therefore lifts the '
             'rate more on a shallow entry than on a deep one. The absolute counts (the '
             'column left of it) are the honest comparison.'
             % (b['pwg_senses_total_known'] / b['n_pilot_groups'],
                a1['pwg_senses_total_known'] / a1['n_pilot_groups']))
    L.append('')

    L.append('## Precision — three defects the keyhole was hiding')
    L.append('')
    L.append('A 60× jump in exact-verse matches is exactly the kind of number that should '
             'be disbelieved until it survives an attack. Removing the sampling limit '
             'exposed three real precision defects in the matcher, all of which are FIXED '
             'here — and the corrected numbers above are the post-fix ones:')
    L.append('')
    L.append('1. **Named books collapsed into one numbering space.** `parse_ref_nums()` '
             'keeps only digits, so DCS\'s `Rām, Bā, 6` and `Rām, Utt, 6` both reduced to '
             '`(6, …)`. One PWG tuple "matched" the same sarga/verse in up to seven '
             'different Rāmāyaṇa books at once — `vara` sense 1a matched Bālakāṇḍa AND '
             'Uttarakāṇḍa simultaneously. Same defect for Suśruta (`Su, Cik., 29`) and '
             'for the 18 Bhagavadgītā chapters (`MBh, 6, BhaGī 1`, read as parvan 6 '
             'adhyāya 1 — not where the Gītā sits). Now `numeric_address()` **abstains** '
             'whenever a post-siglum component is non-numeric.')
    L.append('2. **Chapter-level matches were being reported as exact-verse.** 20.9% of '
             'DCS\'s Ṛgveda and 24.1% of its Atharvaveda sentences carry no '
             '`sent_counter`, so their address stops at the hymn. Those matches are real '
             'but weaker, and now land in their own `locus-chapter` tier (conf 0.70) — '
             'never folded into the exact-verse headline. Both rates are reported '
             'separately throughout.')
    L.append('3. **The Ṛgveda was unreachable through a one-character bug.** '
             '`PWG_TO_DCS_TEXT` keyed the Ṛgveda as ASCII `"RV"`, but PWG\'s abbrev is '
             '`ṚV`. The most canonically-numbered text in the corpus — **50,972 `<ls>` '
             'citations, 6.89% of the dictionary\'s total, second only to the '
             'Mahābhārata** — never matched a single key. It is now the largest single '
             'contributor of exact-verse rows.')
    L.append('')
    L.append('**Regression evidence, stated precisely.** With defects 1 and 2 fixed, '
             're-running the wave-1 configuration (frozen 500, `--locus-scan kwic`) '
             'reproduces all three committed H1455 artifacts — '
             '`sense_corpus_concordance.tsv`, `sense_corpus_coverage.tsv`, '
             '`sense_review_queue.tsv` — with **zero differing lines** (CRLF normalised; '
             'git checks the committed copies out with CRLF). So the matcher is provably '
             'unchanged and wave-1\'s published numbers contained no false positives: its '
             '3-passage sample never happened to land on an unsafe address, and the two '
             'guards only bind once the scan is widened.')
    L.append('')
    L.append('Defect 3 is different and **does** change wave-1\'s own output by design — '
             'reinstating the Ṛgveda takes the frozen frame\'s exact-verse links from 5 '
             'to 12 (17 differing concordance lines). That is a correction, not a '
             'regression: those seven Ṛgveda matches were always there to be found.')
    L.append('')
    L.append('One number in H1632 **is** sharpened rather than reproduced: of its 52 '
             'grounded senses, only **%d were exact-verse** — the other %d were '
             'adhyāya-level Mahābhārata corroboration via the csl-atlas f8 vulgate '
             'crosswalk. The report now carries that split as its own row.'
             % (b['pwg_senses_grounded_verse'],
                b['pwg_senses_grounded'] - b['pwg_senses_grounded_verse']))
    L.append('')

    L.append('## Dictionary-wide re-classification')
    L.append('')
    L.append('The residual classes over all %s PWG headword groups, before and after:'
             % '{:,}'.format(allm['n_pilot_groups']))
    L.append('')
    if old_all:
        L.append('| class | H1632 | H1670 | Δ |')
        L.append('|---|---:|---:|---:|')
        for cls in ('R0_grounding_not_computed', 'R1_lemma_absent_from_dcs',
                    'R2_no_wordsem_tag', 'R3_tagged_but_unaligned',
                    'R4_grounded_alignment'):
            o = old_all['residual_classes'].get(cls, 0)
            n = allm['residual_classes'].get(cls, 0)
            L.append('| `%s` | %s | %s | %+s |'
                     % (cls, '{:,}'.format(o), '{:,}'.format(n),
                        '{:,}'.format(n - o)))
        L.append('')
        r0o = old_all['residual_classes'].get('R0_grounding_not_computed', 0)
        r0n = allm['residual_classes'].get('R0_grounding_not_computed', 0)
        L.append('**`R0_grounding_not_computed` shrank by %s groups (%.1f%%)** — from %s '
                 'to %s — because the aligner now covers %s headword groups instead of '
                 '500. `R4_grounded_alignment` grew from %s to %s.'
                 % ('{:,}'.format(r0o - r0n), 100.0 * (r0o - r0n) / r0o,
                    '{:,}'.format(r0o), '{:,}'.format(r0n),
                    '{:,}'.format(allm['n_groups_grounding_computed']),
                    '{:,}'.format(old_all['residual_classes'].get('R4_grounded_alignment', 0)),
                    '{:,}'.format(allm['residual_classes'].get('R4_grounded_alignment', 0))))
        L.append('')
        L.append('Note what did **not** move: `R1_lemma_absent_from_dcs` fell by only %s '
                 'and `R2_no_wordsem_tag` by %s. Those are the genuine data-availability '
                 'constrictions, and no amount of matcher reach touches them — H1632 was '
                 'right about those two and wrong only about the third.'
                 % ('{:,}'.format(old_all['residual_classes'].get('R1_lemma_absent_from_dcs', 0)
                                  - allm['residual_classes'].get('R1_lemma_absent_from_dcs', 0)),
                    '{:,}'.format(old_all['residual_classes'].get('R2_no_wordsem_tag', 0)
                                  - allm['residual_classes'].get('R2_no_wordsem_tag', 0))))
    L.append('')

    L.append('## Lever B — what a locus crosswalk could still buy')
    L.append('')
    L.append('Every `<ls>` citation on a PWG leaf sense, classified by whether the corpus '
             'side exists at all ([`pwg_ls_dcs_text_crosswalk_backlog.tsv`](%s/pwg_ls_dcs_text_crosswalk_backlog.tsv), '
             '739,503 citations over 4,207 distinct abbrevs):' % BLOB)
    L.append('')
    L.append('| class | abbrevs | citations | share |')
    L.append('|---|---:|---:|---:|')
    L.append('| `MAPPED` (after H1670) | 15 | 269,287 | **36.4%** |')
    L.append('| `DCS-HAS-UNMAPPED` — DCS carries a plausible text, no mapping exists | '
             '443 | 102,546 | **13.9%** |')
    L.append('| `DCS-LACKS` — genuine corpus gap | 3,749 | 367,670 | 49.7% |')
    L.append('')
    L.append('So the residue splits into a **tractable 13.9%** (357 of the 443 are '
             'tuple-comparable — they need a verified map entry, not new data) and an '
             '**untouchable 49.7%** (Pañcatantra, the kośa literature, Manu in '
             'Loiseleur\'s edition, the Oxford catalogue — texts DCS does not carry).')
    L.append('')
    L.append('**A name match is not a crosswalk.** Of nine top candidates inspected, four '
             'were rejected on their `pwgbib` entry: `VP` cites Wilson\'s *translation* by '
             'page; `KĀTY. ŚR` is Kātyāyana\'s *Śrautasūtra* while DCS\'s look-alike is '
             'his *smṛti*; `KAUŚ` numbers kaṇḍikās continuously where DCS numbers per '
             'adhyāya; `KATHĀS` has 124 Brockhaus taraṅgas against DCS\'s 44 chapters. '
             'Only the five whose scheme provably corresponds were mapped. Correcting '
             'H1632: it named **Kathāsaritsāgara** as a text "DCS does not contain" — DCS '
             'carries it (111,298 tokens); the obstacle is the numbering, not the text.')
    L.append('')
    L.append('Working the remaining 443 is [H1691](https://github.com/gasyoun/Uprava/blob/main/handoffs/H1691-Opus_kosha_pwg-dcs-text-crosswalk-beyond-five_26.07.26.md).')
    L.append('')

    L.append('## Lever C — the untagged corpus, kept strictly separate')
    L.append('')
    L.append('An untagged corpus (wisdomlib) cannot raise anything on this page. Every '
             'number above is a **sense-level** grounding, which requires a sense tag to '
             'bind to; an untagged corpus has none, and none can be had without '
             'lemmatising and tagging it ourselves. What it can move is the **lemma-level** '
             'attestation rate — %s of %s PWG headword groups (%.1f%%) have a DCS lemma, '
             'leaving %s (%.1f%%) attested nowhere — and that is a different quantity with '
             'a different denominator.'
             % ('{:,}'.format(allm['n_lemma_attested']),
                '{:,}'.format(allm['n_pilot_groups']),
                100.0 * allm['n_lemma_attested'] / allm['n_pilot_groups'],
                '{:,}'.format(allm['n_pilot_groups'] - allm['n_lemma_attested']),
                100.0 * (1 - allm['n_lemma_attested'] / allm['n_pilot_groups'])))
    L.append('')
    L.append('**No wisdomlib-derived number is reported here, and none was measured into '
             'a sense-level rate.** H1670 deliberately did not consume the scrape: the '
             'lemma-level lane belongs to the wisdomlib-scrape handoffs, and folding it in '
             'here would invite exactly the category error this programme keeps catching.')
    L.append('')

    L.append('## What this does NOT claim')
    L.append('')
    L.append('- **Grounding outside the aligner\'s reach is still UNKNOWN, never 0.** %s '
             'of the %s PWG groups remain `R0_grounding_not_computed`.'
             % ('{:,}'.format(allm['residual_classes'].get('R0_grounding_not_computed', 0)),
                '{:,}'.format(allm['n_pilot_groups'])))
    L.append('- No PWG sense is mapped to a WordNet synset or an MW numbered sense.')
    L.append('- The `overlap` gloss-token tier is reported and **excluded** from every '
             'headline; it is not a sense identification.')
    L.append('- `locus-mbh` and `locus-chapter` are adhyāya/hymn-level **corroboration**, '
             'not exact-verse identity. The exact-verse column is given alongside every '
             'combined figure so neither can be quoted without the other.')
    L.append('- Nothing here says the *remaining* residue is tractable: %.1f%% of PWG\'s '
             'citation mass points at texts DCS does not carry.' % 49.7)
    L.append('')

    L.append('## Reproduce')
    L.append('')
    L.append('```sh')
    L.append('# 1 — the PWG side (needs csl-orig); bulk output is gitignored, the generator is the artifact')
    L.append('cd RussianTranslation/research && python export_frame_sense_loci.py --all')
    L.append('')
    L.append('# 2 — the wide frame: the SAME selection query, run to exhaustion')
    L.append('python ../../../kosha/scripts/select_sense_pilot.py \\')
    L.append('    --input pwg_sense_loci.all.tsv --size 200000 --out frame_wide.tsv')
    L.append('')
    L.append('# 3 — the aligner, per cell (kosha)')
    L.append('python scripts/build_sense_corpus_concordance.py --input <loci> --out-dir run1 --locus-scan kwic')
    L.append('python scripts/build_sense_corpus_concordance.py --input <loci> --out-dir run2 --locus-scan full')
    L.append('python scripts/build_sense_corpus_concordance.py --input <loci> --pilot frame_wide.tsv \\')
    L.append('    --out-dir run5 --locus-scan full')
    L.append('')
    L.append('# 4 — measure each cell, then this synthesis')
    L.append('python pwg_sense_dcs_attestation_pilot.py --frame-mode file --frame frame_wide.tsv \\')
    L.append('    --concordance run5/sense_corpus_concordance.tsv --tag widefulltextmap')
    L.append('python build_grounding_levers_report.py')
    L.append('python pwg_sense_dcs_attestation_pilot.py --selftest')
    L.append('```')
    L.append('')
    L.append('Deterministic, no LLM in the measurement path, no sampling, no RNG. The '
             'aligner lives in [`build_sense_corpus_concordance.py`](%s/build_sense_corpus_concordance.py); '
             'the DCS master is `VisualDCS/src/DCS-data-2026/dcs_full.sqlite` (920,883,200 '
             'bytes — the sibling `src/` and repo-root copies are 0-byte decoys and were '
             'not read).' % KOSHA_BLOB)
    L.append('')
    L.append('_Dr. Mārcis Gasūns_')

    out = os.path.join(a.dir, 'PWG_SENSE_DCS_GROUNDING_LEVERS.md')
    open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')
    print('grounded senses: %d -> %s (%.1f x); rate %.2f%% -> %.2f%%'
          % (b['pwg_senses_grounded'], '{:,}'.format(a12b['pwg_senses_grounded']),
             a12b['pwg_senses_grounded'] / b['pwg_senses_grounded'],
             100 * b['pwg_sense_join_rate'], 100 * a12b['pwg_sense_join_rate']))
    print('wrote %s' % out)


if __name__ == '__main__':
    main()
