#!/usr/bin/env python3
"""Deterministic generator for the PWG->RU research-capability observatory (roadmap card 29).

Reads research/capability_observatory.json (the canonical registry) and emits:
  - CAPABILITY_OBSERVATORY.md  : committed status board, grouped by work package.
  - research/capability_observatory.html : self-contained local filterable view
        (window.OBS_DATA global, opens by double-click, no server / no fetch).

No LLM, no network, no external deps. The only live signal it adds is a probe of
each card's committed `code_inputs` against the working tree: code_inputs are
tracked scripts, so "present"/"missing" is meaningful. `data_inputs` are often
gitignored bulk (corpus_lexicon.jsonl, *_translated.jsonl), so they are declared
only and NOT probed -- absence in-tree does not mean the dataset is missing.

Usage:
    python research/build_observatory.py            # from RussianTranslation/
    python research/build_observatory.py --check     # exit 1 if outputs are stale
"""
import io
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)  # RussianTranslation/
REGISTRY = os.path.join(HERE, "capability_observatory.json")
MD_OUT = os.path.join(ROOT, "CAPABILITY_OBSERVATORY.md")
HTML_OUT = os.path.join(HERE, "capability_observatory.html")

STATUS_DOT = {
    "not-started": "⚪",   # white circle
    "prototype": "\U0001f7e1",  # yellow
    "validated": "\U0001f7e2",  # green
    "blocked": "\U0001f534",    # red
    "shipped": "✅",        # check
}
STATUS_ORDER = {"shipped": 0, "validated": 1, "prototype": 2, "blocked": 3, "not-started": 4}


def load():
    with io.open(REGISTRY, encoding="utf-8") as fh:
        return json.load(fh)


def probe_code(card):
    """Return (present, missing) lists for a card's committed code_inputs."""
    present, missing = [], []
    for rel in card.get("code_inputs", []):
        (present if os.path.exists(os.path.join(ROOT, rel)) else missing).append(rel)
    return present, missing


def counts(cards):
    by_status, by_dep, cheap = {}, {}, 0
    for c in cards:
        by_status[c["status"]] = by_status.get(c["status"], 0) + 1
        for d in c["deps"]:
            by_dep[d] = by_dep.get(d, 0) + 1
        if c.get("cheap"):
            cheap += 1
    return by_status, by_dep, cheap


def render_md(reg):
    meta, packages, cards = reg["meta"], reg["packages"], reg["cards"]
    by_status, by_dep, cheap = counts(cards)
    lines = []
    lines.append("# PWG->RU research-capability observatory")
    lines.append("")
    lines.append("_Created: {} · Last updated: {}_".format(meta["created"], meta["created"]))
    lines.append("")
    lines.append("> Auto-generated by [`research/build_observatory.py`]"
                 "(research/build_observatory.py) from "
                 "[`research/capability_observatory.json`](research/capability_observatory.json). "
                 "Do not hand-edit this file — edit the JSON registry and regenerate.")
    lines.append("")
    lines.append("Status board over the 30 additive research layers in "
                 "[`RESEARCH_CAPABILITY_ROADMAP_2026-07-09.md`](RESEARCH_CAPABILITY_ROADMAP_2026-07-09.md) "
                 "(card 29). Each card carries a **status**, a **dependency flag**, and a "
                 "**confidence in the status label** (not in the layer). A filterable local view "
                 "is at [`research/capability_observatory.html`](research/capability_observatory.html).")
    lines.append("")

    # Legend + rollup
    lines.append("## Rollup")
    lines.append("")
    lines.append("**Status legend:** "
                 + " · ".join("{} {}".format(STATUS_DOT[s], s) for s in STATUS_ORDER))
    lines.append("")
    lines.append("| Status | Cards |")
    lines.append("|---|---:|")
    for s in sorted(by_status, key=lambda x: STATUS_ORDER[x]):
        lines.append("| {} {} | {} |".format(STATUS_DOT[s], s, by_status[s]))
    lines.append("| **Total** | **{}** |".format(len(cards)))
    lines.append("")
    lines.append("**Cheap-derivable (local, deterministic, no gold/external/GPU as the primary gate): "
                 "{} of {} cards.**".format(cheap, len(cards)))
    lines.append("")
    lines.append("| Dependency flag | Cards |")
    lines.append("|---|---:|")
    for d in sorted(by_dep, key=lambda x: -by_dep[x]):
        lines.append("| `{}` | {} |".format(d, by_dep[d]))
    lines.append("")

    # Cheap-first launch order
    cheap_cards = [c for c in cards if c.get("cheap")]
    cheap_cards.sort(key=lambda c: (STATUS_ORDER[c["status"]], c["id"]))
    lines.append("## Cheapest layers to run in parallel with translation")
    lines.append("")
    lines.append("Deterministic, local-only-buildable layers — no external text, no rights "
                 "clearance, no human gold slice, and no GPU model as the *primary* gate. "
                 "Ordered by how far along they already are.")
    lines.append("")
    lines.append("| Card | Layer | Status | Deps | Why cheap |")
    lines.append("|---:|---|---|---|---|")
    for c in cheap_cards:
        deps = ", ".join("`{}`".format(d) for d in c["deps"])
        why = c["coverage_note"].split(". ")[0].rstrip(".") + "."
        lines.append("| {} | {} | {} {} | {} | {} |".format(
            c["id"], c["title"], STATUS_DOT[c["status"]], c["status"], deps, why))
    lines.append("")

    # Per-package detail
    lines.append("## Cards by work package")
    lines.append("")
    pkg_order = list(packages.keys())
    for pk in pkg_order:
        pkg_cards = [c for c in cards if c["package"] == pk]
        pkg_cards.sort(key=lambda c: c["id"])
        lines.append("### {}".format(packages[pk]))
        lines.append("")
        for c in pkg_cards:
            present, missing = probe_code(c)
            ground = ""
            if c.get("code_inputs"):
                bits = []
                if present:
                    bits.append("present: " + ", ".join("`{}`".format(p) for p in present))
                if missing:
                    bits.append("MISSING: " + ", ".join("`{}`".format(m) for m in missing))
                ground = " · code " + "; ".join(bits)
            deps = ", ".join("`{}`".format(d) for d in c["deps"])
            cheap_tag = " · **cheap**" if c.get("cheap") else ""
            lines.append("#### {} {}. {}".format(STATUS_DOT[c["status"]], c["id"], c["title"]))
            lines.append("")
            lines.append("- **Status**: {} (confidence: {}){}".format(c["status"], c["confidence"], cheap_tag))
            lines.append("- **Deps**: {}".format(deps))
            if c.get("claim"):
                lines.append("- **Claim**: {}".format(c["claim"]))
            lines.append("- **State**: {}".format(c["coverage_note"]))
            if c.get("blocker"):
                lines.append("- **Blocker**: {}".format(c["blocker"]))
            lines.append("- **Owner**: {}{}".format(c.get("owner", "-"), ground))
            if c.get("acl_anchor") and c["acl_anchor"] != "-":
                lines.append("- **ACL anchor**: {}".format(c["acl_anchor"]))
            if c.get("related"):
                lines.append("- **Related cards**: {}".format(
                    ", ".join(str(r) for r in c["related"])))
            lines.append("")

    lines.append("_Dr. Mārcis Gasūns_")
    lines.append("")
    return "\n".join(lines)


def render_html(reg):
    payload = json.dumps(reg, ensure_ascii=False)
    dot_map = json.dumps(STATUS_DOT, ensure_ascii=False)
    order_map = json.dumps(STATUS_ORDER)
    # Self-contained: window.OBS_DATA global, no fetch/CORS, opens by double-click.
    return """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PWG-&gt;RU capability observatory</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 system-ui, "Segoe UI", sans-serif; margin: 0; padding: 1.2rem 1.4rem; }
  h1 { font-size: 1.35rem; margin: 0 0 .2rem; }
  .sub { opacity:.75; margin:0 0 1rem; font-size:.9rem; }
  .bar { display:flex; flex-wrap:wrap; gap:.4rem; align-items:center; margin:.6rem 0 1rem; }
  .bar button, .bar select { font: inherit; padding:.25rem .6rem; border-radius:.5rem;
     border:1px solid rgba(128,128,128,.4); background:transparent; color:inherit; cursor:pointer; }
  .bar button.on { background:#3b82f6; color:#fff; border-color:#3b82f6; }
  .pill { font-size:.72rem; padding:.05rem .45rem; border-radius:1rem; border:1px solid rgba(128,128,128,.4); white-space:nowrap; }
  table { border-collapse:collapse; width:100%; font-size:.9rem; }
  th, td { text-align:left; padding:.4rem .55rem; border-bottom:1px solid rgba(128,128,128,.22); vertical-align:top; }
  th { position:sticky; top:0; background:Canvas; cursor:pointer; user-select:none; }
  tr:hover td { background:rgba(128,128,128,.08); }
  .num { text-align:right; color:#888; }
  .note { max-width:46ch; opacity:.9; }
  .cheap { color:#16a34a; font-weight:600; }
  .kpi { display:flex; flex-wrap:wrap; gap:1rem; margin-bottom:1rem; }
  .kpi div { border:1px solid rgba(128,128,128,.3); border-radius:.6rem; padding:.5rem .8rem; }
  .kpi b { font-size:1.3rem; display:block; }
  code { font-size:.82em; }
</style>
</head>
<body>
<h1>PWG-&gt;RU research-capability observatory</h1>
<p class="sub">30 additive research layers &middot; card 29 &middot; generated from capability_observatory.json &middot; local-only, unpublished</p>
<div class="kpi" id="kpi"></div>
<div class="bar" id="filters"></div>
<table id="tbl"><thead><tr>
  <th data-k="id" class="num">#</th>
  <th data-k="title">Layer</th>
  <th data-k="package">Package</th>
  <th data-k="status">Status</th>
  <th data-k="confidence">Conf</th>
  <th data-k="deps">Deps</th>
  <th data-k="cheap">Cheap</th>
  <th data-k="coverage_note">State</th>
</tr></thead><tbody></tbody></table>
<script>
window.OBS_DATA = __PAYLOAD__;
var DOT = __DOTS__, ORDER = __ORDER__;
var reg = window.OBS_DATA, cards = reg.cards, pkgs = reg.packages;
var state = { status:null, dep:null, pkg:null, cheap:false, sortK:"id", sortDir:1 };

function kpi() {
  var by = {}, cheap = 0;
  cards.forEach(function(c){ by[c.status]=(by[c.status]||0)+1; if(c.cheap) cheap++; });
  var el = document.getElementById("kpi");
  var html = '<div><b>' + cards.length + '</b>layers</div>';
  html += '<div><b class="cheap">' + cheap + '</b>cheap-derivable</div>';
  Object.keys(ORDER).sort(function(a,b){return ORDER[a]-ORDER[b];}).forEach(function(s){
    if(by[s]) html += '<div><b>' + (DOT[s]||'') + ' ' + by[s] + '</b>' + s + '</div>';
  });
  el.innerHTML = html;
}
function filters() {
  var el = document.getElementById("filters"), h = '';
  h += '<strong>status</strong> ';
  Object.keys(ORDER).sort(function(a,b){return ORDER[a]-ORDER[b];}).forEach(function(s){
    h += '<button data-t="status" data-v="'+s+'">'+(DOT[s]||'')+' '+s+'</button>';
  });
  h += ' &nbsp;<strong>dep</strong> ';
  var deps = {}; cards.forEach(function(c){c.deps.forEach(function(d){deps[d]=1;});});
  Object.keys(deps).forEach(function(d){ h += '<button data-t="dep" data-v="'+d+'">'+d+'</button>'; });
  h += ' &nbsp;<strong>package</strong> ';
  Object.keys(pkgs).forEach(function(p){ h += '<button data-t="pkg" data-v="'+p+'">'+pkgs[p]+'</button>'; });
  h += ' &nbsp;<button data-t="cheap" data-v="1">cheap only</button>';
  h += ' &nbsp;<button data-t="reset" data-v="">reset</button>';
  el.innerHTML = h;
  el.querySelectorAll("button").forEach(function(b){
    b.onclick = function(){
      var t=b.dataset.t, v=b.dataset.v;
      if(t==="reset"){ state={status:null,dep:null,pkg:null,cheap:false,sortK:state.sortK,sortDir:state.sortDir}; }
      else if(t==="cheap"){ state.cheap=!state.cheap; }
      else { state[t] = (state[t]===v? null : v); }
      draw();
    };
  });
}
function rows() {
  var out = cards.filter(function(c){
    if(state.status && c.status!==state.status) return false;
    if(state.dep && c.deps.indexOf(state.dep)<0) return false;
    if(state.pkg && c.package!==state.pkg) return false;
    if(state.cheap && !c.cheap) return false;
    return true;
  });
  out.sort(function(a,b){
    var k=state.sortK, av=a[k], bv=b[k];
    if(k==="status"){ av=ORDER[a.status]; bv=ORDER[b.status]; }
    if(k==="deps"){ av=a.deps.join(); bv=b.deps.join(); }
    if(av<bv) return -1*state.sortDir; if(av>bv) return 1*state.sortDir; return a.id-b.id;
  });
  return out;
}
function draw() {
  document.querySelectorAll("#filters button").forEach(function(b){
    var t=b.dataset.t, v=b.dataset.v, on=false;
    if(t==="cheap") on=state.cheap; else if(t!=="reset") on=(state[t]===v);
    b.classList.toggle("on", on);
  });
  var tb = document.querySelector("#tbl tbody"); tb.innerHTML="";
  rows().forEach(function(c){
    var tr = document.createElement("tr");
    tr.innerHTML =
      '<td class="num">'+c.id+'</td>'+
      '<td>'+c.title+'</td>'+
      '<td>'+(pkgs[c.package]||c.package)+'</td>'+
      '<td>'+(DOT[c.status]||'')+' '+c.status+'</td>'+
      '<td>'+c.confidence+'</td>'+
      '<td>'+c.deps.map(function(d){return '<span class="pill">'+d+'</span>';}).join(' ')+'</td>'+
      '<td>'+(c.cheap?'<span class="cheap">yes</span>':'')+'</td>'+
      '<td class="note">'+(c.coverage_note||'')+'</td>';
    tb.appendChild(tr);
  });
}
document.querySelectorAll("#tbl th").forEach(function(th){
  th.onclick=function(){ var k=th.dataset.k; if(state.sortK===k) state.sortDir*=-1; else {state.sortK=k; state.sortDir=1;} draw(); };
});
kpi(); filters(); draw();
</script>
</body>
</html>
""".replace("__PAYLOAD__", payload).replace("__DOTS__", dot_map).replace("__ORDER__", order_map)


def main():
    reg = load()
    md = render_md(reg)
    html = render_html(reg)
    check = "--check" in sys.argv
    stale = False
    for path, content in ((MD_OUT, md), (HTML_OUT, html)):
        old = None
        if os.path.exists(path):
            with io.open(path, encoding="utf-8") as fh:
                old = fh.read()
        if old != content:
            stale = True
            if not check:
                with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(content)
    if check:
        if stale:
            print("STALE: outputs differ from registry; run build_observatory.py", file=sys.stderr)
            sys.exit(1)
        print("OK: observatory outputs current")
        return
    n = len(reg["cards"])
    cheap = sum(1 for c in reg["cards"] if c.get("cheap"))
    print("wrote {} ({} cards, {} cheap) and {}".format(
        os.path.relpath(MD_OUT, ROOT), n, cheap, os.path.relpath(HTML_OUT, ROOT)))


if __name__ == "__main__":
    main()
