"""Phase 4 of HERITAGE_INRIA_ROADMAP.md: morphology-forms oracle.

Builds a THIRD independent witness for Sanskrit inflected-form data from the
Heritage Platform's own current morphology databank (SL_morph.xml, dict v3.81,
2026-06-21, generated by Huet's rule-based declension/conjugation engine) and
diffs it against kosha's existing DCS-attested + vidyut-generated forms layer
(kosha/data/db/kosha.db `forms` table, 426,410 form->lemma pairs). This is a
COMPARISON / ORACLE only -- it never writes to kosha and never merges either
side. Genuine cross-engine disagreements are the valuable output.

Join key: the SLP1 form string (both sides are already SLP1). Heritage stems
carry a `#N` homonymy index (same convention as mw_heritage_crosswalk.tsv);
kosha lemmas do not, so `#N` is stripped before lemma-set comparison.

Provenance: Heritage morphology (c) Gerard Huet 1994-2026, LGPLLR; composition
with kosha's CC BY-SA data approved by Huet 03-07-2026 (HERITAGE_INRIA_ROADMAP.md
Sec.2). Raw XML stays gitignored under heritage_mirror/; only this derived diff
is committed.

Inputs:
  heritage_mirror/manual/SL_morph.xml.gz   (gitignored, ~184MB decompressed)
  ../../kosha/data/db/kosha.db  `forms`    (SanskritRussian dcs+vidyut feeds)

Outputs (this directory):
  heritage_forms_oracle.tsv.gz             full intersection, agreement-flagged
  heritage_forms_oracle_disagreements.tsv  disjoint-lemma rows only (browsable)
  heritage_forms_oracle_stats.json         machine-readable summary
  heritage_only_forms.tsv                  H111 kosha ingest feed: form_slp1 ·
                                            lemma_slp1 (bare stem) · heritage_category,
                                            one row per (stem, category) pair, for the
                                            forms absent from kosha's `forms` table.
"""
import sys, os, re, gzip, csv, json, sqlite3
import xml.etree.ElementTree as ET

sys.stdout.reconfigure(encoding='utf-8'); sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
SL_MORPH = os.path.join(HERE, "heritage_mirror", "manual", "SL_morph.xml.gz")
KOSHA_DB = os.path.normpath(os.path.join(HERE, "..", "..", "kosha", "data", "db", "kosha.db"))

OUT_FULL = os.path.join(HERE, "heritage_forms_oracle.tsv.gz")
OUT_DIS = os.path.join(HERE, "heritage_forms_oracle_disagreements.tsv")
OUT_STATS = os.path.join(HERE, "heritage_forms_oracle_stats.json")
OUT_ONLY = os.path.join(HERE, "heritage_only_forms.tsv")

HASH_N = re.compile(r'#\d+$')

# SLP1 consonants (for the "nasal followed by a consonant" test)
CONS = set("kKgGNcCjJYwWqQRtTdDnpPbBmyrlvSzsh")
NASALS = set("MNYRnm")


def nasal_norm(s):
    """Canonicalise the anusvara / homorganic-nasal convention mismatch.

    DCS writes word-final and pre-consonant nasalisation as anusvara `M`
    (AvAsaM, oMkAra, BayaMkara); Heritage's declension engine writes the
    phonetic homorganic nasal (AvAsam, oNkAra, BayaNkara). Both conventions
    neutralise in exactly the positions handled here, so mapping any nasal to
    a single `M` when word-final or pre-consonant makes the two comparable.
    A nasal before a vowel (a genuine onset, e.g. -ana-, -ama-) is left as-is.
    Applied symmetrically to both sides -- a canonicalisation, not a rewrite of
    either source.
    """
    if not s:
        return s
    out = []
    n = len(s)
    for i, c in enumerate(s):
        if c in NASALS and (i == n - 1 or s[i + 1] in CONS):
            out.append('M')
        else:
            out.append(c)
    return ''.join(out)


def norm_set(strings):
    return {nasal_norm(x) for x in strings}


def prefix_related(a_set, b_set, minlen=3):
    """True if some lemma in a_set is a prefix of some lemma in b_set (or vice
    versa) with the shorter >= minlen -- a proxy for root<->derived-stem
    granularity (garh/garhita, Ir/Iray, cint/cintay)."""
    for a in a_set:
        for b in b_set:
            if a == b:
                continue
            lo, hi = (a, b) if len(a) <= len(b) else (b, a)
            if len(lo) >= minlen and hi.startswith(lo):
                return True
    return False

# coarse category from the first non-<s> child tag of an <f> element
CAT = {
    'na': 'nominal', 'v': 'finite-verb', 'pa': 'participle',
    'vu': 'verbal-indecl', 'uf': 'indeclinable',
    'iic': 'iic-compound', 'iiv': 'iiv-compound', 'iip': 'iip-compound',
    'avya': 'avyayibhava', 'ab': 'absolutive', 'iip': 'iip-compound',
}


def load_kosha():
    """form_slp1 -> (frozenset(lemma), frozenset(source)) from kosha.db forms."""
    con = sqlite3.connect(KOSHA_DB)
    lem = {}
    src = {}
    for form, lemma, source in con.execute(
            "SELECT form_slp1, lemma_slp1, source FROM forms"):
        lem.setdefault(form, set()).add(lemma)
        src.setdefault(form, set()).add(source)
    con.close()
    return lem, src


def stream_heritage(kosha_forms):
    """Single pass over SL_morph.xml.gz.

    Returns:
      n_f          total <f> elements
      hforms       set of ALL distinct heritage form strings
      inter        form -> [set(bare_stem), set(category)] for forms also in kosha
      honly        form -> [set(bare_stem), set(category)] for forms NOT in kosha
                   (H111 kosha-ingest feed)
    """
    n_f = 0
    hforms = set()
    hnorm = set()
    inter = {}
    honly = {}
    with gzip.open(SL_MORPH, 'rb') as fh:
        context = ET.iterparse(fh, events=('start', 'end'))
        _, root = next(context)  # <forms>
        for event, elem in context:
            if event != 'end' or elem.tag != 'f':
                continue
            n_f += 1
            form = elem.get('form')
            hforms.add(form)
            hnorm.add(nasal_norm(form))
            s = elem.find('s')
            stem = HASH_N.sub('', s.get('stem')) if s is not None else ''
            cat = 'other'
            for child in elem:
                if child.tag != 's':
                    cat = CAT.get(child.tag, child.tag)
                    break
            if form in kosha_forms:
                bucket = inter.get(form)
                if bucket is None:
                    inter[form] = [{stem}, {cat}]
                else:
                    bucket[0].add(stem)
                    bucket[1].add(cat)
            else:
                bucket = honly.get(form)
                if bucket is None:
                    honly[form] = [{stem}, {cat}]
                else:
                    bucket[0].add(stem)
                    bucket[1].add(cat)
            root.clear()
            if n_f % 200000 == 0:
                print(f"  ...{n_f} forms parsed", flush=True)
    return n_f, hforms, hnorm, inter, honly


def main():
    if not os.path.exists(SL_MORPH):
        sys.exit(f"missing {SL_MORPH}")
    if not os.path.exists(KOSHA_DB):
        sys.exit(f"missing {KOSHA_DB}")

    print("loading kosha baseline (dcs+vidyut) ...", flush=True)
    kosha_lem, kosha_src = load_kosha()
    print(f"  kosha distinct forms: {len(kosha_lem)}", flush=True)

    print("streaming Heritage SL_morph.xml ...", flush=True)
    n_f, hforms, hnorm, inter, honly = stream_heritage(set(kosha_lem.keys()))
    print(f"  heritage <f> elements: {n_f}", flush=True)
    print(f"  heritage distinct forms: {len(hforms)}", flush=True)

    # buckets (raw form-string join)
    inter_forms = set(inter.keys())
    heritage_only = len(hforms) - len(inter_forms)
    kosha_only = len(kosha_lem) - len(inter_forms)

    # nasal-normalised overlap: how much of the raw gap is the anusvara/nasal
    # transcription-convention mismatch rather than a real coverage difference
    knorm = norm_set(kosha_lem.keys())
    norm_inter = len(hnorm & knorm)
    # cleaner measure: raw kosha-only forms that DO match a Heritage form once
    # the anusvara/nasal convention is normalised (a convention-masked gap, not
    # a real coverage gap)
    kosha_only_forms = set(kosha_lem.keys()) - inter_forms
    kosha_only_recovered = sum(1 for f in kosha_only_forms if nasal_norm(f) in hnorm)
    # DCS sandhi-context avagraha artifacts (leading apostrophe) never appear in
    # Heritage's citation-form declension tables
    kosha_only_avagraha = sum(1 for f in kosha_only_forms if f.startswith("'"))

    n_agree = n_disagree = 0
    dis_rows = []
    full_rows = []
    for form in sorted(inter_forms):
        hstems, hcats = inter[form]
        klem = kosha_lem[form]
        ksrc = kosha_src[form]
        agree = not hstems.isdisjoint(klem)
        flag = 'agree' if agree else 'disagree'
        dclass = ''
        if agree:
            n_agree += 1
        else:
            n_disagree += 1
            # classify the disagreement
            if not norm_set(hstems).isdisjoint(norm_set(klem)):
                dclass = 'nasal-variant'          # false: anusvara/nasal only
            elif prefix_related(hstems, klem):
                dclass = 'stem-granularity'        # root<->derived-stem policy
            else:
                dclass = 'genuine-or-ambiguous'    # the interesting residue
        row = (form, flag,
               '|'.join(sorted(hstems)),
               '|'.join(sorted(klem)),
               '|'.join(sorted(hcats)),
               '|'.join(sorted(ksrc)),
               dclass)
        full_rows.append(row)
        if not agree:
            dis_rows.append(row)

    header = ['form_slp1', 'flag', 'heritage_stems', 'kosha_lemmas',
              'heritage_category', 'kosha_sources', 'disagreement_class']

    with gzip.open(OUT_FULL, 'wt', encoding='utf-8', newline='') as f:
        w = csv.writer(f, delimiter='\t', lineterminator='\n')
        w.writerow(header)
        w.writerows(full_rows)

    with open(OUT_DIS, 'w', encoding='utf-8', newline='') as f:
        w = csv.writer(f, delimiter='\t', lineterminator='\n')
        w.writerow(header)
        w.writerows(dis_rows)

    # H111 kosha-ingest feed: one row per (form, stem, category) for forms
    # kosha does not have at all. `honly` keys are exactly hforms - inter_forms.
    only_rows = []
    for form in sorted(honly):
        stems, cats = honly[form]
        for stem in sorted(stems):
            for cat in sorted(cats):
                only_rows.append((form, stem, cat))
    with open(OUT_ONLY, 'w', encoding='utf-8', newline='') as f:
        w = csv.writer(f, delimiter='\t', lineterminator='\n')
        w.writerow(['form_slp1', 'lemma_slp1', 'heritage_category'])
        w.writerows(only_rows)

    # disagreement breakdowns
    from collections import Counter
    dis_by_cat = Counter(r[4] for r in dis_rows)
    dis_by_class = Counter(r[6] for r in dis_rows)

    n_inter = len(inter_forms)
    stats = {
        'heritage_dict_version': '3.81 (2026-06-21)',
        'heritage_f_elements': n_f,
        'heritage_distinct_forms': len(hforms),
        'kosha_distinct_forms': len(kosha_lem),
        'kosha_pairs': sum(len(v) for v in kosha_lem.values()),
        'intersection_forms': n_inter,
        'agree': n_agree,
        'disagree': n_disagree,
        'agree_pct_of_intersection': round(100 * n_agree / max(1, n_inter), 2),
        'disagree_pct_of_intersection': round(100 * n_disagree / max(1, n_inter), 2),
        'heritage_only_forms': heritage_only,
        'kosha_only_forms': kosha_only,
        'coverage_of_kosha_by_heritage_pct': round(100 * n_inter / max(1, len(kosha_lem)), 2),
        'coverage_of_heritage_by_kosha_pct': round(100 * n_inter / max(1, len(hforms)), 2),
        'nasal_normalised_overlap_forms': norm_inter,
        'nasal_norm_coverage_of_kosha_pct': round(100 * norm_inter / max(1, len(knorm)), 2),
        'kosha_only_recovered_by_nasal_norm': kosha_only_recovered,
        'kosha_only_avagraha_artifacts': kosha_only_avagraha,
        'heritage_only_forms_feed_rows': len(only_rows),
        'disagreement_by_class': dict(dis_by_class.most_common()),
        'disagreement_by_heritage_category': dict(dis_by_cat.most_common()),
    }
    with open(OUT_STATS, 'w', encoding='utf-8') as f:
        json.dump(stats, f, ensure_ascii=False, indent=2)

    print("\n=== ORACLE SUMMARY ===")
    for k, v in stats.items():
        print(f"  {k}: {v}")
    print(f"\nwritten: {OUT_FULL}")
    print(f"written: {OUT_DIS} ({len(dis_rows)} rows)")
    print(f"written: {OUT_ONLY} ({len(only_rows)} rows, H111 kosha ingest feed)")
    print(f"written: {OUT_STATS}")


if __name__ == "__main__":
    main()
