#!/usr/bin/env python
r"""H1210 arm B — the shared Opus controller round-trip, driven from Python.

Arm A runs the controller inline (same Workflow, same script). Arm B generates from Python,
so its controller stage is the standalone `control_template.js` Workflow and this script is
the shuttle between them. Two phases, run alternately until the attempt budget is spent:

  build  <slice_result> <round>   -> control payload (+ injected .wf.js) for every card whose
                                     status is `pending-controller` (free gate clean, but the
                                     card is complexity-flagged or the worker self-reported
                                     unsure — the same trigger set arm A uses)
  apply  <slice_result> <verdicts> -> approved cards become `clean-controller-approved`;
                                     rejected cards are REGENERATED by DeepSeek with the
                                     controller's own issues as feedback (the same
                                     "retry with concrete remarks" chain arm A runs), then
                                     re-gated and re-marked `pending-controller` if they
                                     still need review, or `escalate-review-sheet` once the
                                     3-attempt budget is exhausted.

Rejection is sticky here exactly as in the JS (B06): a controller-rejected card can never
exit as `clean-no-review` on a later attempt.

Usage:
  python src/pilot/h1210/arm_b_control.py build src/pilot/h1210/arm_b.slice_result.json 1
  # ...run the emitted .wf.js through the Workflow tool, save its return value as JSON...
  python src/pilot/h1210/arm_b_control.py apply src/pilot/h1210/arm_b.slice_result.json \
         src/pilot/h1210/arm_b.control_r1.verdicts.json --env-file <.env>
"""
import argparse
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import det_gate            # noqa: E402
import deepseek_arm as ds  # noqa: E402

PAYLOAD_DIR = HERE
MAX_ATTEMPTS = ds.MAX_ATTEMPTS


def senses_of(card, field='russian'):
    """Per-sense rows for the shared controller; field is russian/english (H2226 OPT-4)."""
    return [{'tag': s.get('tag'), 'german': s.get('german'), field: s.get(field)}
            for r in (card.get('records') or []) for s in (r.get('senses') or [])]


def _controller_prompt_for_field(field):
    """Same template as h1209.prep_slice.controller_prompt_for_field (kept local so
    arm_b_control does not import across the h1209 package path at module load)."""
    lang = 'English' if field == 'english' else 'Russian'
    pair = 'German->English' if field == 'english' else 'German->Russian'
    return (
        'You are the QUALITY CONTROLLER for a PWG %s scholarly dictionary translation. '
        'For headword {key1}, check each sense: (a) the %s faithfully renders the German gloss '
        '(no invented, dropped, or merged meaning), (b) every {Tn} placeholder present in the German is a real '
        'masked span (not invented), (c) scholarly-philological register. Set ok=false with specific, actionable '
        'issues ONLY for genuine fidelity defects; do NOT nitpick style or wording preference. Senses JSON:\n'
        % (pair, lang)
    )


def _resolve_field(a):
    """Prefer --manifest / --slice-payload field; fall back to --field / russian."""
    if getattr(a, 'manifest', None):
        return load(a.manifest).get('field') or a.field or 'russian'
    if getattr(a, 'slice_payload', None):
        return load(a.slice_payload).get('field') or a.field or 'russian'
    return a.field or 'russian'


def load(p):
    return json.load(open(p, encoding='utf-8'))


def save(p, obj):
    with open(p, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(obj, f, ensure_ascii=False, indent=1)
        f.write('\n')
    print('wrote', p)


def cmd_build(a):
    res = load(a.slice_result)
    cards = {c['key1']: c['card'] for c in res['cards_out']}
    pending = [r for r in res['results'] if r['final_status'] == 'pending-controller']
    if not pending:
        print('no cards pending controller review — nothing to build')
        return 0
    field = _resolve_field(a)
    payload = {
        'schema': 'h1210.control.v1',
        'arm': res.get('arm', 'B_deepseek'),
        'round': a.round,
        # H2226 OPT-4: control_template.js reads these; no second EN scaffold.
        'field': field,
        'controller_prompt': _controller_prompt_for_field(field),
        'cards': [{'key1': r['key1'],
                   'senses': senses_of(cards[r['key1']] or {}, field)}
                  for r in pending],
    }
    p = os.path.join(PAYLOAD_DIR, 'arm_b.control_r%d.payload.json' % a.round)
    save(p, payload)
    tpl = open(os.path.join(HERE, 'control_template.js'), encoding='utf-8').read()
    out = tpl.replace('/*__PAYLOAD__*/ null /*__END__*/',
                      json.dumps(payload, ensure_ascii=False))
    wf = os.path.join(PAYLOAD_DIR, 'arm_b.control_r%d.wf.js' % a.round)
    with open(wf, 'w', encoding='utf-8', newline='\n') as f:
        f.write(out)
    size = os.path.getsize(wf)
    print('wrote %s (%d cards, field=%s, %d bytes)'
          % (wf, len(payload['cards']), field, size))
    if size > 512 * 1024:
        print('WARNING: %d bytes exceeds the 512 KB Workflow scriptPath ceiling — split it' % size)
    return 0


def cmd_apply(a):
    res = load(a.slice_result)
    payload = load(a.payload)
    verdicts = {v['key1']: v.get('verdict') for v in load(a.verdicts)['verdicts']}
    rows = {r['key1']: r for r in res['results']}
    cards = {c['key1']: c for c in res['cards_out']}
    slice_cards = {c['key1']: c for c in load(a.slice_payload)['cards']}
    common = load(a.slice_payload)['prompt_common']
    man = load(a.manifest)
    field = man.get('field') or 'russian'

    env = ds.load_env_file(a.env_file)
    key = os.environ.get('DEEPSEEK_API_KEY') or env.get('DEEPSEEK_API_KEY')
    base = (os.environ.get('DEEPSEEK_BASE_URL') or env.get('DEEPSEEK_BASE_URL')
            or 'https://api.deepseek.com')
    model = (os.environ.get('DEEPSEEK_MODEL') or env.get('DEEPSEEK_MODEL') or 'deepseek-chat')

    sys.path.insert(0, os.path.join(os.path.dirname(HERE), 'h1209'))
    import build_args  # noqa: E402
    schema = {'type': 'object', 'additionalProperties': False,
              'required': ['card', 'self_report'],
              'properties': {'card': {'$ref': '#/$defs/card'},
                             'self_report': build_args.SELF_REPORT},
              '$defs': man['output_schema']['$defs']}
    system = ds.SYSTEM_TMPL % json.dumps(schema, ensure_ascii=False)

    client = None
    approved = rejected = null_verdict = regenerated = 0
    extra_calls = []
    for c in payload['cards']:
        k = c['key1']
        row = rows[k]
        v = verdicts.get(k)
        row['controller_calls'] = (row.get('controller_calls') or 0) + 1
        if v is None:
            # A null verdict is NEVER approval (same rule as the inline arm-A path). With
            # --null-retry it stays `pending-controller` so the next round re-reviews it:
            # a controller-side DEADLINE is an infrastructure artifact, and parking the
            # card as escalated would charge arm B a review-sheet row it never earned.
            null_verdict += 1
            row['controller_ok'] = None
            row['controller_calls'] -= 1        # a timed-out call produced no verdict
            row['controller_issues'] = ['controller returned no verdict (deadline/failure)']
            row['final_status'] = ('pending-controller' if a.null_retry
                                   else 'escalate-review-sheet')
            continue
        if v.get('ok'):
            approved += 1
            row['controller_ok'] = True
            row['controller_issues'] = v.get('issues') or []
            row['final_status'] = 'clean-controller-approved'
            row['would_promote'] = True
            continue
        rejected += 1
        row['controller_ok'] = False
        row['controller_issues'] = v.get('issues') or ['unspecified']
        if row['attempts'] >= MAX_ATTEMPTS:
            row['final_status'] = 'escalate-review-sheet'
            row['would_promote'] = False
            continue
        if a.no_regen:
            row['final_status'] = 'escalate-review-sheet'
            row['would_promote'] = False
            continue
        # Regenerate with the controller's own remarks — arm A's retry chain, verbatim.
        if client is None:
            if not key:
                sys.exit('FAIL: no DEEPSEEK_API_KEY — cannot run the controller-feedback retry')
            client = ds.DeepSeek(base, key, model, a.max_tokens)
        sc = slice_cards[k]
        feedback = 'Controller found issues:\n- ' + '\n- '.join(row['controller_issues'])
        user = (common + sc['card_block']
                + '\n\n=== CONTROLLER FEEDBACK (fix ONLY these, keep everything else verbatim) ===\n'
                + feedback)
        text, call = client.chat(system, user, '%s#retry%d' % (k, row['attempts'] + 1))
        extra_calls.append(call)
        row['attempts'] += 1
        regenerated += 1
        if text is None:
            row['final_status'] = 'escalate-review-sheet'
            row['would_promote'] = False
            continue
        try:
            obj, _repair = ds.extract_json(text)
            card = obj.get('card')
            if not isinstance(card, dict):
                raise ValueError('no `card` object in reply')
        except ValueError as e:
            row['final_status'] = 'escalate-review-sheet'
            row['would_promote'] = False
            row.setdefault('repairs', []).append('retry: %s' % e)
            continue
        cards[k]['card'] = card
        det = det_gate.deterministic_audit(card, sc, field)
        row['coverage'] = det['coverage']
        row['det_issues'] = det['issues']
        if det['issues'] or row['attempts'] >= MAX_ATTEMPTS:
            # Out of attempts, or the free gate now fails: park it — never auto-approve.
            row['final_status'] = 'escalate-review-sheet'
            row['would_promote'] = False
        else:
            # Sticky rejection (B06): must pass the controller, cannot exit clean-no-review.
            row['final_status'] = 'pending-controller'
            row['would_promote'] = False
        print('  regenerated %-24s attempts=%d -> %s' % (k, row['attempts'], row['final_status']))

    res['results'] = [rows[r['key1']] for r in res['results']]
    res['cards_out'] = [cards[c['key1']] for c in res['cards_out']]
    res.setdefault('control_rounds', []).append({
        'round': payload['round'], 'reviewed': len(payload['cards']),
        'approved': approved, 'rejected': rejected, 'null_verdict': null_verdict,
        'regenerated': regenerated,
        'retry_calls': extra_calls,
        'retry_cost': client.cost() if client else None,
    })
    save(a.slice_result, res)
    print('round %d: reviewed=%d approved=%d rejected=%d null=%d regenerated=%d'
          % (payload['round'], len(payload['cards']), approved, rejected, null_verdict,
             regenerated))
    still = sum(1 for r in res['results'] if r['final_status'] == 'pending-controller')
    print('still pending controller: %d' % still)
    return 0


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest='cmd', required=True)
    b = sub.add_parser('build')
    b.add_argument('slice_result')
    b.add_argument('round', type=int)
    b.add_argument('--field', default=None,
                   help='target field russian/english (default: from --manifest/--slice-payload or russian)')
    b.add_argument('--manifest', default=None,
                   help='execution manifest; field is read from it when present')
    b.add_argument('--slice-payload', default=None,
                   help='h1209/h1210 slice payload; field is read from it when present')
    ap2 = sub.add_parser('apply')
    ap2.add_argument('slice_result')
    ap2.add_argument('verdicts')
    ap2.add_argument('--payload', required=True)
    ap2.add_argument('--slice-payload', required=True)
    ap2.add_argument('--manifest', required=True)
    ap2.add_argument('--env-file', default=None)
    ap2.add_argument('--max-tokens', type=int, default=8192)
    ap2.add_argument('--null-retry', action='store_true',
                     help='leave deadline-nulled verdicts pending for the next round instead '
                          'of escalating them')
    ap2.add_argument('--no-regen', action='store_true',
                     help='record the verdicts but do not spend on the feedback retry')
    a = ap.parse_args()
    sys.exit(cmd_build(a) if a.cmd == 'build' else cmd_apply(a))


if __name__ == '__main__':
    main()
