"""Emit a reviewable, deduplicated list of high-confidence NWS source defects
with the exact offending delimiter located in context. Feeds the Halle erratum.

Classes (high→medium confidence):
  PAREN_UNCLOSED  — an opening '(' with no matching ')'  (excess-open; the
                    enumeration convention `1) 2)` only adds excess ')', so
                    excess '(' is a genuine unclosed paren)
  DOUBLE_OPEN     — a stray doubled '(('
  BRACKET_IMBAL   — unbalanced editorial '[' ']' (medium confidence; review)

Run: python _nws_defect_list.py
"""
import json, os, sys, glob, re
sys.stdout.reconfigure(encoding='utf-8')

NWS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'pilot', 'nws')

def locate_unmatched_open(t, op='(', cl=')'):
    """Return index of the first unmatched opening delimiter, else -1."""
    stack = []
    for i, ch in enumerate(t):
        if ch == op:
            stack.append(i)
        elif ch == cl:
            if stack:
                stack.pop()
    return stack[0] if stack else -1

def locate_unmatched_close(t, op='[', cl=']'):
    depth = 0
    for i, ch in enumerate(t):
        if ch == op:
            depth += 1
        elif ch == cl:
            depth -= 1
            if depth < 0:
                return i
    return -1

def win(t, i, w=40):
    return t[max(0, i-w):i+w].replace('\n', ' ')

paren, dbl, brk = [], [], []
DBL = re.compile(r'\(\s*\(')

for path in glob.iglob(os.path.join(NWS_DIR, '*.json')):
    base = os.path.basename(path)
    if base.startswith('_keys') or base.startswith('_nws'):
        continue
    try:
        d = json.load(open(path, encoding='utf-8'))
    except Exception:
        continue
    t = d.get('nws') or ''
    if not t:
        continue
    k1, ia = d.get('key1', ''), d.get('iast', '')
    op, cl = t.count('('), t.count(')')

    if op > cl:
        i = locate_unmatched_open(t)
        paren.append((ia, k1, win(t, i) if i >= 0 else t[:80]))
    m = DBL.search(t)
    if m:
        dbl.append((ia, k1, win(t, m.start())))
    if t.count('[') != t.count(']'):
        i = locate_unmatched_close(t, '[', ']')
        if i < 0:
            i = locate_unmatched_open(t, '[', ']')
        brk.append((ia, k1, win(t, i) if i >= 0 else t[:80]))

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'NWS_SOURCE_DEFECTS.md')

# de-dup double-open entries that are already explained by an unclosed paren
paren_keys = {k1 for _, k1, _ in paren}
dbl_new = [r for r in dbl if r[1] not in paren_keys]

lines = []
def w(s=''):
    lines.append(s)

total = len({k1 for _, k1, _ in paren} | {k1 for _, k1, _ in dbl} | {k1 for _, k1, _ in brk})
w('# NWS source-data defects — structural delimiter scan')
w('')
w('Generated by [`src/_nws_defect_list.py`](src/_nws_defect_list.py) over the full')
w('scraped NWS corpus (34,101 entries with NWS content). These are defects in the')
w('NWS source itself (dropped/swapped parentheses and editorial brackets), found')
w('independently of owner-attribution — which is why the attribution audit')
w('([NWS_AUDIT_REPORT.md](NWS_AUDIT_REPORT.md)) surfaced only the one that also')
w('breaks an owner cite (`vṛtrakhādá`). Most sit mid-gloss and are inherited from')
w('condensing Monier-Williams parentheticals.')
w('')
w('**%d distinct entries.** Confidence: the paren and double-open classes are high'
  % total)
w('(excess *opening* parens cannot arise from the `1) 2)` enumeration convention,')
w('which only adds closing `)`); the bracket class is high but worth a human glance')
w('before sending, as a few `[ ]` could be intentional nesting.')
w('')

# per-entry suggested fixes for the bracket class (judgment-confirmed by hand)
BRK_FIX = {
    'aS': "insert the missing closing `]` after the `[a) … b) …]` editorial note",
    'brahman': "`Brahma[-Götter)` → `Brahma(-Götter)` (`[` should be `(`)",
    'Dar': "two `]` → `)`: `(Abl oder Abl mit ā́ ]` and the parallel aside",
    'etad': "`(Akk n von etád ]` → `(Akk n von etád )` (`]` should be `)`)",
    'gam': "`(Lok, Adv des Ortes]` → `… Ortes)` (`]` should be `)`)",
    'gar': "`(Lok, ádhi mit Lok]` → `… mit Lok)` (`]` should be `)`)",
    'guRa': "insert the missing closing `]` after `[e.g. viśiṣṭo daśabhir guṇaiḥ …`",
    'gA': "`(Lok oder Adv des Ortes]` → `… Ortes)` (`]` should be `)`)",
    'jYA': "`(Akk des Inf]` → `(Akk des Inf)` (`]` should be `)`)",
    'lok': "`investigates [=, … vyavalo °)` → `(=, … vyavalo °)` (`[` should be `(`)",
    'muktikA': "insert the missing closing `]` after `[contrasted in Mvy with …`",
    'nu': "insert the missing closing `]` after `[ nū́ cit : …`",
    'ruh': "insert the missing closing `]` after `[very commonly of planting roots …`",
    'saMSaya': "`CarakaSaṃ [vim] 8.43]` → delete the stray trailing `]` after `8.43`",
    'viS': "`eingehen in (Akk, Lok)];` → delete the stray `]` after `)`",
    'vizRu': "insert the missing closing `]` after `[esp. with Indra whom he assists …`",
}

def section(title, rows, note, fixes=None):
    w('## %s (%d)' % (title, len(rows)))
    w('')
    w(note)
    w('')
    for ia, k1, c in sorted(rows):
        w('- **%s** (`%s`) — …%s…' % (ia, k1, c))
        if fixes and k1 in fixes:
            w('    - **Fix:** %s' % fixes[k1])
    w('')

section('Unmatched opening parenthesis — a closing `)` is missing', paren,
        'Fix: insert the dropped `)` at the end of the parenthetical aside shown.')
section('Stray doubled `((` (not already covered above)', dbl_new,
        'Fix: delete the extra `(`.')
section('Unbalanced editorial brackets `[ ]`', brk,
        'Each carries a per-entry fix (hand-confirmed): a `]` typed for `)` '
        '(6), a `[` for `(` (2), a stray `]` to delete (2), or a missing '
        'closing `]` to insert (6).', fixes=BRK_FIX)

open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('wrote', OUT, '—', total, 'distinct entries',
      '(paren %d, double-new %d, bracket %d)' % (len(paren), len(dbl_new), len(brk)))
