#!/usr/bin/env python
r"""Document every <ls> literary-source citation in the PWG article corpus and
report how many resolve to a Cologne scan page.

Reads the same stores the article site is built from
(`pwg_ru_translated.jsonl` DE/RU fields + `wf_output.en.<root>.json` german/
english), extracts each `<ls n="PREFIX">VISIBLE</ls>` citation, resolves it via
`ls_resolver` (PWG paths), and writes three reports + their JSON siblings to
the PWG repo's literary-source area (pwg_ls/pwg_ru_coverage/) when PWG is a
sibling checkout, else locally; override with --out-dir:

  * CITATION_SOURCES.md    -- abbreviation -> scan/HTML target + coverage summary
  * UNCOVERED_SOURCES.md   -- most-cited works with no Cologne target
  * COVERAGE_COMPARISON.md -- covered vs uncovered + coverage frontier + provenance
  * {citation,uncovered,coverage}_*.json -- the same data, machine-readable

  python src/build_citation_index.py [--out-dir DIR]
"""
import glob
import json
import os
import re
import sys
from collections import Counter, defaultdict
from datetime import date

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

# First-generated date (fixed); last-regenerated is stamped live each build.
CREATED = '02-07-2026'
REGENERATED = date.today().strftime('%d-%m-%Y')
GEN_NOTE = ('_Created: %s · Last regenerated: %s · auto-generated by '
            'build_citation_index.py — do not edit by hand._' % (CREATED, REGENERATED))

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import ls_resolver as lsr  # noqa: E402

REPO = os.path.dirname(HERE)                       # RussianTranslation/
RU_STORE = os.path.join(HERE, 'pwg_ru_translated.jsonl')

# The reports LIVE in the PWG repo (pwg_ls/pwg_ru_coverage — the literary-source
# work's home) when it is checked out as a sibling; else they fall back to this
# RussianTranslation dir. Override with `--out-dir`.
_PWG = os.path.abspath(os.path.join(REPO, '..', '..', 'PWG'))
_DEFAULT_OUTDIR = (os.path.join(_PWG, 'pwg_ls', 'pwg_ru_coverage')
                   if os.path.isdir(_PWG) else REPO)


def set_outdir(outdir):
    """Point every report/JSON output at `outdir`."""
    global OUTDIR, OUT_MD, OUT_JSON, OUT_UNCOVERED, OUT_UNCOVERED_JSON
    global OUT_COMPARISON, OUT_COMPARISON_JSON
    OUTDIR = outdir
    OUT_MD = os.path.join(outdir, 'CITATION_SOURCES.md')
    OUT_JSON = os.path.join(outdir, 'citation_sources.json')
    OUT_UNCOVERED = os.path.join(outdir, 'UNCOVERED_SOURCES.md')
    OUT_UNCOVERED_JSON = os.path.join(outdir, 'uncovered_sources.json')
    OUT_COMPARISON = os.path.join(outdir, 'COVERAGE_COMPARISON.md')
    OUT_COMPARISON_JSON = os.path.join(outdir, 'coverage_comparison.json')


set_outdir(_DEFAULT_OUTDIR)

# PWG blob base for cross-links between the three reports (their published home).
PWG_COV_URL = 'https://github.com/sanskrit-lexicon/PWG/blob/main/pwg_ls/pwg_ru_coverage'

_LS = re.compile(r'<ls\b([^>]*)>(.*?)</ls>', re.S)
_N_ATTR = re.compile(r'\bn\s*=\s*"([^"]*)"')
# Abbreviation = leading run up to the first digit / the n= prefix, trimmed.
_ABBR = re.compile(r'^\s*([^0-9]*?)\s*[0-9]')


def abbr_of(n_attr, visible):
    """Human-meaningful grouping label: the source abbreviation. Prefer the n=
    prefix (carries the inherited work for bare-number continuation refs); fall
    back to the visible text."""
    for s in (n_attr, visible):
        if not s:
            continue
        m = _ABBR.match(s)
        if m and m.group(1).strip():
            return m.group(1).strip()
        if s.strip():
            return s.strip()
    return '?'


def iter_ls():
    """Yield (attrs, visible) for every <ls> in every DE/RU/EN source field."""
    if os.path.exists(RU_STORE):
        with open(RU_STORE, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                r = json.loads(line)
                for fld in ('de', 'ru'):
                    for m in _LS.finditer(r.get(fld) or ''):
                        yield m.group(1), m.group(2)
    for fp in glob.glob(os.path.join(REPO, 'wf_output.en.*.json')):
        try:
            d = json.load(open(fp, encoding='utf-8'))
        except Exception:
            continue
        for e in d.get('results') or []:
            c = e.get('card')
            if not c:
                continue
            for rec in c.get('records') or []:
                for s in rec.get('senses') or []:
                    for fld in ('german', 'english'):
                        for m in _LS.finditer(s.get(fld) or ''):
                            yield m.group(1), m.group(2)


def host_repo(url):
    """Extract the scan-repo slug + a normalized template from a resolved URL."""
    m = re.match(r'https?://([^/]+)/([^?#]*)', url)
    if not m:
        return url, url
    host, path = m.group(1), m.group(2)
    repo = path.split('/')[0] if 'scans.github.io' in host or 'lexicon.github.io' in host else host
    templ = re.sub(r'[0-9]+', 'N', url)
    return repo, templ


def build():
    groups = defaultdict(lambda: {'total': 0, 'resolved': 0, 'scan': 0, 'html': 0,
                                   'sample_url': None, 'sample_ref': None,
                                   'repos': set(), 'templates': set()})
    total = resolved = 0
    counts = {'scan': 0, 'html': 0}
    seen = set()
    for attrs, visible in iter_ls():
        m = _N_ATTR.search(attrs or '')
        n_attr = m.group(1) if m else None
        vis = (visible or '').strip()
        key = (n_attr, vis)
        # de/ru/en repeat the same citations across senses; count DISTINCT refs
        # so the index measures the reference set, not sense multiplicity.
        if key in seen:
            continue
        seen.add(key)
        label = abbr_of(n_attr, vis)
        g = groups[label]
        g['total'] += 1
        total += 1
        try:
            url = lsr.generate_href('pwg', n_attr, vis)
        except Exception:
            url = None
        if url:
            g['resolved'] += 1
            resolved += 1
            t = lsr.link_type(url)
            g[t] = g.get(t, 0) + 1
            counts[t] = counts.get(t, 0) + 1
            repo, templ = host_repo(url)
            g['repos'].add(repo)
            g['templates'].add(templ)
            if g['sample_url'] is None:
                g['sample_url'] = url
                g['sample_ref'] = ((n_attr or '') + vis).strip()
    return groups, total, resolved, counts


def emit(groups, total, resolved, counts):
    rows = sorted(groups.items(), key=lambda kv: (-kv[1]['total'], kv[0]))
    scan_n, html_n = counts.get('scan', 0), counts.get('html', 0)
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    data = {
        'total_distinct_refs': total, 'resolved': resolved,
        'resolved_scan': scan_n, 'resolved_html': html_n,
        'coverage_pct': round(100 * resolved / total, 1) if total else 0,
        'distinct_abbreviations': len(groups),
        'abbreviations': [{
            'abbr': k, 'total': v['total'], 'resolved': v['resolved'],
            'scan': v['scan'], 'html': v['html'],
            'repos': sorted(v['repos']), 'sample_ref': v['sample_ref'],
            'sample_url': v['sample_url'],
        } for k, v in rows],
    }
    with open(OUT_JSON, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    def pct(n):
        return 100 * n / total if total else 0

    unresolved_rows = [(k, v) for k, v in rows if v['resolved'] < v['total']]
    L = []
    L.append('# PWG citation sources — abbreviation → source-link index')
    L.append('')
    L.append(GEN_NOTE)
    L.append('')
    L.append('Every `<ls>` literary-source citation in the PWG article corpus '
             '(the roots published at '
             '[gasyoun.github.io/SanskritLexicography]'
             '(https://gasyoun.github.io/SanskritLexicography/)), grouped by '
             'source abbreviation, with the Cologne target each links to. A '
             'target is either a **scan** (photographed book pages, on '
             '`sanskrit-lexicon-scans.github.io` or the Cologne westergaard '
             'Dhātupāṭha viewer) or **HTML** (rendered digital text — the '
             '`rvlinks`/`avlinks` hymn pages and external `ashtadhyayi.com` '
             'Pāṇini sūtras). Links are generated by [`ls_resolver.py`]'
             '(https://github.com/gasyoun/SanskritLexicography/blob/master/RussianTranslation/src/ls_resolver.py) '
             '— a Python port of the canonical resolver in '
             '[`csl-app/lib/core/ls_service.dart`]'
             '(https://github.com/sanskrit-lexicon/csl-app/blob/main/lib/core/ls_service.dart).')
    L.append('')
    L.append('## Coverage')
    L.append('')
    L.append('| metric | value |')
    L.append('|---|---:|')
    L.append('| distinct citation references | %d |' % total)
    L.append('| resolved to a source link | %d (%.1f%%) |' % (resolved, pct(resolved)))
    L.append('| &nbsp;&nbsp;• to a scan (page image) | %d (%.1f%%) |' % (scan_n, pct(scan_n)))
    L.append('| &nbsp;&nbsp;• to HTML (digital text) | %d (%.1f%%) |' % (html_n, pct(html_n)))
    L.append('| unresolved | %d |' % (total - resolved))
    L.append('| distinct abbreviations | %d |' % len(groups))
    L.append('')
    L.append('> **Coverage is target-limited, not resolver-limited.** The resolver '
             'implements essentially the full mapping set the Cologne app itself '
             'supports; most unresolved references cite works the Cologne project '
             'has **not digitized** (no scan repository exists — e.g. Suśruta, most '
             'Upaniṣads, the Śrauta/Gṛhya sūtras, several chrestomathies), so they '
             'cannot be linked from anywhere.')
    L.append('')
    L.append('> The most-cited uncovered works are ranked (by how often each is '
             'actually cited) in [`UNCOVERED_SOURCES.md`]'
             '(https://github.com/sanskrit-lexicon/PWG/blob/main/pwg_ls/pwg_ru_coverage/UNCOVERED_SOURCES.md), '
             'regenerated on every build.')
    L.append('')
    L.append('## Abbreviation index')
    L.append('')
    L.append('| abbreviation | refs | resolved | scan | HTML | target | example |')
    L.append('|---|---:|---:|---:|---:|---|---|')
    for k, v in rows:
        repos = ', '.join(sorted(v['repos'])) or '—'
        if v['sample_url']:
            ex = '[%s](%s)' % (v['sample_ref'] or v['sample_url'], v['sample_url'])
        else:
            ex = '—'
        L.append('| %s | %d | %d | %d | %d | %s | %s |' %
                 (k.replace('|', '\\|'), v['total'], v['resolved'],
                  v['scan'], v['html'], repos, ex))
    L.append('')
    if unresolved_rows:
        L.append('## Unresolved abbreviations (no Cologne target yet)')
        L.append('')
        L.append('These citations render as plain (dim) text on the site because no '
                 'source mapping resolved them — either no scan/HTML exists in the '
                 'Cologne ecosystem, or they are grammatical authorities/cross-refs '
                 'that are not linkable. Candidates for the PWG `<ls>` link-target '
                 'program (Dictionary-to-Book) where a scan does exist.')
        L.append('')
        L.append('| abbreviation | unresolved refs |')
        L.append('|---|---:|')
        for k, v in sorted(unresolved_rows, key=lambda kv: -(kv[1]['total'] - kv[1]['resolved'])):
            L.append('| %s | %d |' % (k.replace('|', '\\|'), v['total'] - v['resolved']))
        L.append('')
    L.append('_Dr. Mārcis Gasūns_')
    with open(OUT_MD, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')


# ---------------------------------------------------------------------------
# Occurrence analysis (how OFTEN each source is cited, vs how many DISTINCT refs)
# ---------------------------------------------------------------------------
# The distinct-ref counts above measure the *reference set*. To measure how
# often a source is actually cited we count every <ls> as it appears in the
# displayed corpus. That corpus is the build_article_site union model (RU∪EN
# deduplicated per sense) — counting the raw stores instead would multiply by
# the DE/RU/EN fields and the store overlap. We read the raw DE source per
# displayed sense (de_raw), which keeps the <ls n="..."> attribute, so a bare
# continuation inherits its parent work and grouping uses the true prefix.


def occurrence_stats():
    """Count every <ls> as it appears on the displayed DE surface (occurrences).

    Returns (occ_scan, occ_html, per, total) where per[abbr] = {'res','unres'}
    occurrence counts. An abbreviation with res==0 is *truly uncovered* (no
    occurrence resolves anywhere → no Cologne target); res>0 with unres>0 is a
    resolution edge-case (the work is digitized, a few refs are malformed)."""
    sys.path.insert(0, os.path.join(HERE, 'pilot'))
    import build_article_site as bas
    model = bas.build_model()
    occ_scan = occ_html = total = labels = 0
    per = defaultdict(lambda: {'res': 0, 'unres': 0, 'scan': 0, 'html': 0})
    for r in model:
        for sc in r['subcards']:
            for s in sc['senses']:
                for m in _LS.finditer(s.get('de_raw') or ''):
                    total += 1
                    nm = _N_ATTR.search(m.group(1) or '')
                    n_attr = nm.group(1) if nm else None
                    vis = (m.group(2) or '').strip()
                    try:
                        url = lsr.generate_href('pwg', n_attr, vis)
                    except Exception:
                        url = None
                    t = lsr.link_type(url)
                    if t == 'scan':
                        occ_scan += 1
                        g = per[abbr_of(n_attr, vis)]
                        g['res'] += 1
                        g['scan'] += 1
                    elif t == 'html':
                        occ_html += 1
                        g = per[abbr_of(n_attr, vis)]
                        g['res'] += 1
                        g['html'] += 1
                    elif not re.search(r'[0-9]', (n_attr or '') + vis):
                        # <ls> with no coordinate = an edition/cross-ref LABEL
                        # ("ed. Bomb.", "ebend."), never a linkable reference.
                        labels += 1
                    else:
                        per[abbr_of(n_attr, vis)]['unres'] += 1
    return occ_scan, occ_html, per, total, labels


def emit_uncovered(per, occ_scan, occ_html, occ_total, labels):
    """Live list of the most-cited sources with NO link, most frequent first.

    `per[abbr] = {'res','unres'}`. Truly-uncovered = res==0 (no target exists);
    edge-cases (res>0, unres>0) are listed separately — the work is digitized,
    only some refs are malformed."""
    uncovered = {k: v['unres'] for k, v in per.items() if v['res'] == 0 and v['unres'] > 0}
    edge = {k: v['unres'] for k, v in per.items() if v['res'] > 0 and v['unres'] > 0}
    rows = sorted(uncovered.items(), key=lambda kv: (-kv[1], kv[0]))
    un_total = sum(uncovered.values())
    occ_resolved = occ_scan + occ_html
    data = {
        'occurrences_total': occ_total,
        'occurrences_linked': occ_resolved,
        'occurrences_scan': occ_scan, 'occurrences_html': occ_html,
        'occurrences_uncovered': un_total,
        'occurrences_noncoordinate_labels': labels,
        'distinct_uncovered_works': len(uncovered),
        'uncovered': [{'abbr': k, 'occurrences': n} for k, n in rows],
        'edge_case_misses': [{'abbr': k, 'unresolved': n}
                             for k, n in sorted(edge.items(), key=lambda kv: -kv[1])],
    }
    with open(OUT_UNCOVERED_JSON, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    L = []
    L.append('# PWG uncovered citation sources — most-cited works with no link')
    L.append('')
    L.append(GEN_NOTE)
    L.append('')
    L.append('Works cited by `<ls>` in the PWG article corpus that **have no Cologne '
             'target at all** — *no* occurrence resolves, because no scan repo exists '
             'in the [`sanskrit-lexicon-scans`](https://github.com/orgs/sanskrit-lexicon-scans/repositories) '
             'org (or the abbreviation is a grammatical authority / cross-reference, '
             'not a citable text). Ranked by **how often the work is actually cited** '
             '(occurrences on the displayed DE surface), most-cited first — so the top '
             'rows are the highest-value targets should Cologne ever digitize them. '
             'Regenerated on every build by [`build_citation_index.py`]'
             '(https://github.com/gasyoun/SanskritLexicography/blob/master/RussianTranslation/src/build_citation_index.py).')
    L.append('')
    L.append('Of **%s** citation occurrences on the site, **%s** link out '
             '(%s scan + %s HTML) and **%s (%.1f%%)** stay unlinked. The unlinked '
             'ones are **%d truly-uncovered works** below (%s occurrences), plus %d '
             'edge-case misses in otherwise-covered works (see end) and %s '
             'non-coordinate `<ls>` labels (edition/cross-ref notes like '
             '"ed. Bomb.", never linkable).'
             % (f'{occ_total:,}', f'{occ_resolved:,}', f'{occ_scan:,}', f'{occ_html:,}',
                f'{occ_total - occ_resolved:,}', 100 * (occ_total - occ_resolved) / occ_total if occ_total else 0,
                len(uncovered), f'{un_total:,}', sum(edge.values()), f'{labels:,}'))
    L.append('')
    L.append('| rank | source (abbreviation) | citations |')
    L.append('|---:|---|---:|')
    for i, (k, n) in enumerate(rows, 1):
        L.append('| %d | %s | %d |' % (i, k.replace('|', '\\|'), n))
    L.append('')
    if edge:
        L.append('## Edge-case misses (work IS digitized; some refs malformed)')
        L.append('')
        L.append('These abbreviations resolve for most citations — the counts below '
                 'are individual references with a malformed/unusual coordinate that '
                 'the resolver could not parse. Not "uncovered".')
        L.append('')
        L.append('| source | unresolved refs |')
        L.append('|---|---:|')
        for k, n in sorted(edge.items(), key=lambda kv: -kv[1]):
            L.append('| %s | %d |' % (k.replace('|', '\\|'), n))
        L.append('')
    L.append('_Dr. Mārcis Gasūns_')
    with open(OUT_UNCOVERED, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')


def emit_comparison(per, occ_scan, occ_html, occ_total, labels):
    """Side-by-side comparison of COVERED vs UNCOVERED works, by citation
    frequency (occurrences), plus the coverage frontier — how much occurrence
    coverage would rise if the top-N uncovered works were digitized."""
    covered = sorted(((k, v) for k, v in per.items() if v['res'] > 0),
                     key=lambda kv: -kv[1]['res'])
    uncovered = sorted(((k, v['unres']) for k, v in per.items()
                        if v['res'] == 0 and v['unres'] > 0), key=lambda kv: -kv[1])
    occ_resolved = occ_scan + occ_html
    un_total = sum(n for _, n in uncovered)

    def pct(n):
        return 100 * n / occ_total if occ_total else 0

    data = {
        'occurrences_total': occ_total,
        'covered': occ_resolved, 'covered_scan': occ_scan, 'covered_html': occ_html,
        'uncovered': un_total, 'noncoordinate_labels': labels,
        'covered_works': len(covered), 'uncovered_works': len(uncovered),
        'top_covered': [{'abbr': k, 'occ': v['res'], 'scan': v['scan'], 'html': v['html']}
                        for k, v in covered[:50]],
        'top_uncovered': [{'abbr': k, 'occ': n} for k, n in uncovered[:50]],
    }
    with open(OUT_COMPARISON_JSON, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)

    L = []
    L.append('# PWG citation coverage — covered vs uncovered')
    L.append('')
    L.append(GEN_NOTE)
    L.append('')
    L.append('A side-by-side of the two halves: citations that resolve to a Cologne '
             'source (**covered** — see [`CITATION_SOURCES.md`]'
             '(https://github.com/sanskrit-lexicon/PWG/blob/main/pwg_ls/pwg_ru_coverage/CITATION_SOURCES.md)) '
             'vs those that do not (**uncovered** — see [`UNCOVERED_SOURCES.md`]'
             '(https://github.com/sanskrit-lexicon/PWG/blob/main/pwg_ls/pwg_ru_coverage/UNCOVERED_SOURCES.md)). '
             'Everything here is counted by **occurrence** (how often a work is '
             'actually cited on the displayed DE surface), not distinct references.')
    L.append('')
    L.append('## The split')
    L.append('')
    L.append('| bucket | occurrences | share |')
    L.append('|---|---:|---:|')
    L.append('| **covered** (links out) | %s | %.1f%% |' % (f'{occ_resolved:,}', pct(occ_resolved)))
    L.append('| &nbsp;&nbsp;• scan (page images) | %s | %.1f%% |' % (f'{occ_scan:,}', pct(occ_scan)))
    L.append('| &nbsp;&nbsp;• HTML (digital text) | %s | %.1f%% |' % (f'{occ_html:,}', pct(occ_html)))
    L.append('| **uncovered** (no Cologne target) | %s | %.1f%% |' % (f'{un_total:,}', pct(un_total)))
    L.append('| non-referential labels (never linkable) | %s | %.1f%% |' % (f'{labels:,}', pct(labels)))
    L.append('| **total** | %s | 100%% |' % f'{occ_total:,}')
    L.append('')
    L.append('%d works are covered; %d works are uncovered. So most *works* are '
             'uncovered, but the covered ones are the heavily-cited backbone (epics, '
             'purāṇas, kāvya, the Vedic saṃhitās), so ~%.0f%% of actual citations '
             'resolve.' % (len(covered), len(uncovered), pct(occ_resolved)))
    L.append('')
    L.append('## Most-cited works — covered vs uncovered (top 20 each)')
    L.append('')
    L.append('| # | covered work | cites | target | uncovered work | cites |')
    L.append('|--:|---|--:|---|---|--:|')
    for i in range(20):
        if i < len(covered):
            ck, cv = covered[i]
            tgt = 'scan' if cv['scan'] >= cv['html'] else 'HTML'
            if cv['scan'] and cv['html']:
                tgt = 'scan+HTML'
            cstr = '%s | %d | %s' % (ck.replace('|', '\\|'), cv['res'], tgt)
        else:
            cstr = ' |  | '
        if i < len(uncovered):
            uk, un = uncovered[i]
            ustr = '%s | %d' % (uk.replace('|', '\\|'), un)
        else:
            ustr = ' | '
        L.append('| %d | %s | %s |' % (i + 1, cstr, ustr))
    L.append('')
    L.append('## Coverage frontier — value of digitizing the top uncovered works')
    L.append('')
    L.append('The uncovered tail is long (%d works) but front-loaded. If the '
             'most-cited uncovered works gained a Cologne scan, occurrence coverage '
             '(now %.1f%%) would rise as follows:' % (len(uncovered), pct(occ_resolved)))
    L.append('')
    L.append('| digitize top-N uncovered | adds citations | new coverage |')
    L.append('|---:|---:|---:|')
    cum = 0
    marks = [1, 5, 10, 25, 50, 100]
    for n in marks:
        if n > len(uncovered):
            break
        add = sum(x for _, x in uncovered[:n])
        newcov = 100 * (occ_resolved + add) / occ_total if occ_total else 0
        L.append('| %d | +%s | %.1f%% |' % (n, f'{add:,}', newcov))
    allcov = 100 * (occ_resolved + un_total) / occ_total if occ_total else 0
    L.append('| all %d | +%s | %.1f%% |' % (len(uncovered), f'{un_total:,}', allcov))
    L.append('')
    L.append('_(Ceiling < 100%% because %s occurrences are non-referential `<ls>` '
             'labels — edition/cross-ref notes with no locus.)_' % f'{labels:,}')
    L.append('')
    # Static provenance (historical git facts) — records when/by-whom the coverage
    # was built, so the "when/who" sits next to the numbers.
    L.append('## Provenance — when the coverage was built, and by whom')
    L.append('')
    L.append('The links express **months-old Cologne work**, mostly *surfaced* (not '
             'created) in this session. Timeline, oldest first:')
    L.append('')
    L.append('| layer | when | who | what | contribution to the covered set |')
    L.append('|---|---|---|---|---|')
    L.append('| Page scans | prior years | Cologne Digital Sanskrit Dictionaries project | '
             'digitised the source editions (~100 `sanskrit-lexicon-scans` repos) | '
             'the link targets themselves |')
    L.append('| Resolver mappings | 2026-03 → 2026-05 | `csl-app` maintainers '
             '(Dictionary-to-Book `<ls>` program) | abbreviation→scan/HTML URL logic in '
             '`ls_service.dart` (41 commits) + `ls_patterns.dart` (34) — 34 in Mar, 16 in '
             'Apr, 2 in May 2026, then none | **~98.6%** of covered refs |')
    L.append('| Chrestomathie mapping | 2026-07-02 | this session | `Chr.` / `BENF. Chr.` → '
             '`bchrest2` (in the Python port; upstream [csl-app#49]'
             '(https://github.com/sanskrit-lexicon/csl-app/pull/49) awaiting maintainer '
             'review) | **+1.4%** (473 refs) |')
    L.append('| Python port + site application | 2026-07-02 | this session | ported the '
             'resolver to [`ls_resolver.py`]'
             '(https://github.com/gasyoun/SanskritLexicography/blob/master/RussianTranslation/src/ls_resolver.py); '
             'citation links rendered on the site for the **first time** (0 before) | '
             'made the whole covered set *visible* |')
    L.append('| Measurement + docs | 2026-07-02 | this session | this comparison + '
             '`CITATION_SOURCES.md` + `UNCOVERED_SOURCES.md` | — |')
    L.append('')
    L.append('In short: the coverage **logic** is the Cologne March–May 2026 effort; this '
             'session added ~1.4% of the mappings and made the whole set live and measured '
             'on the site. Site work by Opus 4.8 (`claude-opus-4-8`), with the Dart→Python '
             'port done by a Sonnet 5 (`claude-sonnet-5`) sub-agent.')
    L.append('')
    L.append('_Dr. Mārcis Gasūns_')
    with open(OUT_COMPARISON, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(L) + '\n')


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--out-dir', help='where to write the reports '
                    '(default: sibling PWG/pwg_ls/pwg_ru_coverage, else local)')
    args = ap.parse_args()
    if args.out_dir:
        set_outdir(os.path.abspath(args.out_dir))
    os.makedirs(OUTDIR, exist_ok=True)
    groups, total, resolved, counts = build()
    emit(groups, total, resolved, counts)
    occ_scan, occ_html, per, occ_total, labels = occurrence_stats()
    emit_uncovered(per, occ_scan, occ_html, occ_total, labels)
    emit_comparison(per, occ_scan, occ_html, occ_total, labels)
    occ_resolved = occ_scan + occ_html
    print('citation index: %d distinct refs, %d resolved (%.1f%%), %d abbreviations'
          % (total, resolved, 100 * resolved / total if total else 0, len(groups)))
    print('  -> %s' % OUT_MD)
    print('  -> %s' % OUT_JSON)
    print('occurrences (displayed DE surface): %d total, %d linked '
          '(scan %d / HTML %d), %d unlinked'
          % (occ_total, occ_resolved, occ_scan, occ_html, occ_total - occ_resolved))
    if occ_resolved:
        print('  scan:HTML by occurrence = %.1f : 1  (by distinct ref = %.1f : 1)'
              % (occ_scan / occ_html if occ_html else 0,
                 counts['scan'] / counts['html'] if counts['html'] else 0))
    print('  -> %s' % OUT_UNCOVERED)
    print('  -> %s' % OUT_COMPARISON)


if __name__ == '__main__':
    main()
