#!/usr/bin/env python
"""pwg_ru stage-4 corpus gate — deterministic join + corpus query.

Joins a PWG headword (SLP1 key) to the five extracted Sanskrit→Russian
dictionaries in this directory and (optionally) to the SamudraManthanam
verse-aligned parallel corpus, assembling the input the LLM verdict prompt
(pwg_ru_prompts/4_korpus_proverka.txt) consumes. It also offers a cheap,
tunable heuristic correctness pre-check (the LLM is the real verdict).

This is CODE (committed); the dictionary data it reads (src/*.jsonl) is
gitignored and regenerated by build_src.py. The corpus query REUSES
SamudraManthanam's corpus.db (read-only) — it does not duplicate the corpus.

Modes:
  python corpus_gate.py lookup  <key1> [key2]      one headword → glosses + examples
  python corpus_gate.py card    <key1> "<pwg_ru>"  emit the 4_korpus input JSON + deterministic precheck
  python corpus_gate.py coverage [N]               per-signal coverage over PWG
  python corpus_gate.py tune     [N]               inter-dictionary agreement → threshold
"""
import atexit, json, os, re, sys, sqlite3, unicodedata, random
from collections import defaultdict

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
GITHUB = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
PWG_KEY1 = os.path.join(HERE, '..', '..', 'HeadwordLists', 'then-2014', 'PWG-unique-key1-106085.txt')
CORPUS_DB = os.environ.get('SAMUDRA_CORPUS_DB',
                           os.path.join(GITHUB, 'SamudraManthanam', 'web', 'corpus.db'))
_CORPUS_CON = None

# ---- tunables ------------------------------------------------------------
# THRESHOLD tuned by `tune` (inter-dictionary agreement): two independent human
# dictionaries share head-term tokens only at LOW overlap (synonyms/paraphrase),
# so a high bar is a confident auto-PASS, but anything below is routed to the LLM
# (4_korpus_proverka.txt) — it is NOT auto-divergence. Only the LLM declares
# 'divergence'. 0.5 = at least half the pwg_ru head tokens appear in one gloss.
THRESHOLD = 0.5
HEAD_SENSE_ONLY = True     # compare only sense 1 (text before the first ';')
MAX_GLOSS_PER_SOURCE = 4   # cap glosses fed per source
# --------------------------------------------------------------------------

INDEP = ['koch', 'kna', 'fri', 'smirnov']   # independent correctness authorities
REF = 'kow'                                  # WIL-seeded human PWG→RU reference
NAME = {'koch': 'Кочергина', 'kna': 'Кнауэр', 'fri': 'Фриш',
        'smirnov': 'Смирнов', 'kow': 'Коссович'}

# Specialist name-glossaries (built by build_glossaries.py from SamudraManthanam's
# raw Data/*.txt "index of names" appendices, NOT the corpus_builder/jsonl
# pipeline build_src.py reads). Text-specific proper-noun vocabularies, not
# general-purpose dictionaries -- kept OUT of INDEP so they never enter the
# heuristic() correctness score or coverage/tune stats; they are corroborating
# evidence only, surfaced alongside the real INDEP signal in build_card().
SPECIALIST = ['grin12', 'grin3']
SPECIALIST_NAME = {'grin12': 'Гринцер (Рамаяна I-II)', 'grin3': 'Гринцер (Рамаяна III)'}

# Third-language (Hindi) SENSE signal — indic-dict, built by build_indic.py.
# These gloss in HINDI, not Russian, so they are NOT a correctness vote and are
# deliberately kept OUT of the Russian-token heuristic(). Their only role is soft
# SENSE-disambiguation (which sense is primary), reported alongside the corpus
# signal: it may corroborate, never decides, never withholds. Rights: free use
# with attribution (indic-dict maintainer, email 2026-06-24); see
# INDIC_DICT_EVALUATION.md. apte_hi is Apte-aligned (structured sense map);
# vedic_rituals_hi is a Vedic-ritual top-up.
SENSE = ['apte_hi', 'vedic_rituals_hi']
SENSE_NAME = {'apte_hi': 'Apte→हिन्दी', 'vedic_rituals_hi': 'Vedic-rituals→हिन्दी'}

# Rights status per source for the PUBLISHED edition. EVERY source is both a
# correctness signal and, where useful, publishable text: the project owner has
# secured approvals for extensive use of the modern Sanskrit-Russian sources.
# Keep provenance/attribution, but do not downgrade approved modern sources to
# evidence-only.
RIGHTS = {
    'koch':    {'publishable': True, 'status': 'approved-modern', 'basis': 'copyright approval on file'},
    'smirnov': {'publishable': True, 'status': 'approved-modern', 'basis': 'copyright approval on file'},
    'fri':     {'publishable': True, 'status': 'approved-modern', 'basis': 'copyright approval on file'},
    'kna':     {'publishable': True,  'status': 'public-domain', 'basis': 'Ф.И. Кнауэр d.1917 → PD'},
    'kow':     {'publishable': True,  'status': 'public-domain', 'basis': 'К.А. Коссович d.1883 → PD (cite as reference)'},
    # Specialist glossaries: rights NOT yet confirmed (Гринцер translations,
    # 1995/2006) -- default evidence-only per guardrail until checked.
    'grin12':  {'publishable': False, 'status': 'rights-unconfirmed', 'basis': 'evidence-only pending rights check'},
    'grin3':   {'publishable': False, 'status': 'rights-unconfirmed', 'basis': 'evidence-only pending rights check'},
}


def publishable(code):
    return RIGHTS.get(code, {}).get('publishable', False)

# SLP1 -> IAST (for corpus search / display)
_S2I = {'A':'ā','I':'ī','U':'ū','f':'ṛ','F':'ṝ','x':'ḷ','X':'ḹ','E':'ai','O':'au',
        'M':'ṃ','H':'ḥ','N':'ṅ','Y':'ñ','w':'ṭ','W':'ṭh','q':'ḍ','Q':'ḍh','R':'ṇ',
        'S':'ś','z':'ṣ','K':'kh','G':'gh','C':'ch','J':'jh','T':'th','D':'dh',
        'P':'ph','B':'bh'}

def form_key(s):
    """Length-preserving SLP1 normalization for joining (keeps case/length;
    drops accents, slashes, hyphen bounds — NOT a naive NFD-strip-Mn)."""
    if not s:
        return ''
    s = unicodedata.normalize('NFC', s.strip())
    s = re.sub(r'[̀-ͯ]', '', s)
    s = s.replace('/', '').replace('\\', '').replace('|', '').replace(' ', '')
    return s.strip('-')

def slp1_to_ascii(s):
    """SLP1 -> diacritic-free lowercase roman, for FTS search."""
    iast = ''.join(_S2I.get(c, c) for c in form_key(s))
    nfd = unicodedata.normalize('NFD', iast)
    return ''.join(c for c in nfd if not unicodedata.combining(c)).lower()

# ---- dictionary index ----------------------------------------------------
# Which correctness-authority source files were present at the last load_index().
# FL7 (architecture audit 2026-07-02 / code review 2026-07-04): an absent evidence
# jsonl was silently skipped, so "no independent gloss" could mean EITHER "sources
# not built" OR "this headword is genuinely uncovered" — indistinguishable. This
# set lets build_card mark evidence_unavailable explicitly instead of degrading
# to an unmarked LLM-verdict.
SOURCES_PRESENT = set()


def evidence_status():
    """'ok' if >=1 independent correctness authority (INDEP) is loaded; else
    'evidence_unavailable' — meaning a 'no independent gloss' precheck reflects
    MISSING SOURCES, not an uncovered headword. Fail loud rather than silently
    degrade to the LLM verdict as if the evidence had been consulted and found
    nothing."""
    return 'ok' if any(c in SOURCES_PRESENT for c in INDEP) else 'evidence_unavailable'


def load_index():
    idx = defaultdict(lambda: defaultdict(list))
    SOURCES_PRESENT.clear()
    for code in INDEP + [REF]:
        path = os.path.join(HERE, code + '.jsonl')
        if not os.path.exists(path):
            continue
        SOURCES_PRESENT.add(code)
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                e = json.loads(line)
                k = form_key(e.get('slp1', ''))
                if k:
                    idx[k][code].append(e.get('gloss', ''))
    return idx

def lookup(idx, key1, key2=None):
    hit = idx.get(form_key(key1))
    if not hit and key2:
        hit = idx.get(form_key(key2))
    hit = hit or {}
    indep = [{'source': NAME[c], 'code': c, 'gloss': g, 'publishable': publishable(c)}
             for c in INDEP for g in hit.get(c, [])[:MAX_GLOSS_PER_SOURCE]]
    kow = hit.get(REF, [])[:MAX_GLOSS_PER_SOURCE]
    return indep, kow

# ---- specialist name-glossaries (corroborating evidence, not INDEP) ---------
_SPECIALIST_IDX = None
def load_specialist_index():
    global _SPECIALIST_IDX
    if _SPECIALIST_IDX is not None:
        return _SPECIALIST_IDX
    idx = defaultdict(lambda: defaultdict(list))
    for code in SPECIALIST:
        path = os.path.join(HERE, code + '.jsonl')
        if not os.path.exists(path):
            continue
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                e = json.loads(line)
                k = form_key(e.get('slp1', ''))
                if k:
                    idx[k][code].append(e.get('gloss', ''))
    _SPECIALIST_IDX = idx
    return idx

def lookup_specialist(key1, key2=None):
    sidx = load_specialist_index()
    hit = sidx.get(form_key(key1))
    if not hit and key2:
        hit = sidx.get(form_key(key2))
    hit = hit or {}
    return [{'source': SPECIALIST_NAME[c], 'code': c, 'gloss': g, 'publishable': publishable(c)}
            for c in SPECIALIST for g in hit.get(c, [])[:MAX_GLOSS_PER_SOURCE]]

# ---- Hindi sense index (soft third-language signal, separate from INDEP) ------
_SENSE_IDX = None
def load_sense_index():
    """apte_hi / vedic_rituals_hi indexed under BOTH the faithful citation key and
    the bare stem (build_indic.to_stem) — apte-hi prints nominatives (agniH), PWG
    keys on stems (agni)."""
    global _SENSE_IDX
    if _SENSE_IDX is not None:
        return _SENSE_IDX
    idx = defaultdict(lambda: defaultdict(list))
    for code in SENSE:
        path = os.path.join(HERE, code + '.jsonl')
        if not os.path.exists(path):
            continue
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                e = json.loads(line)
                rec = {'pos': e.get('pos', ''), 'gloss': e.get('gloss', ''),
                       'dev': e.get('dev', ''), 'attribution': e.get('attribution', '')}
                for k in {form_key(e.get('slp1', '')), form_key(e.get('stem', ''))}:
                    if k:
                        idx[k][code].append(rec)
    _SENSE_IDX = idx
    return idx

def lookup_sense(key1, key2=None):
    sidx = load_sense_index()
    hit = sidx.get(form_key(key1))
    if not hit and key2:
        hit = sidx.get(form_key(key2))
    hit = hit or {}
    return [{'source': SENSE_NAME[c], 'code': c, 'pos': r['pos'],
             'gloss': r['gloss'], 'dev': r['dev'], 'attribution': r['attribution']}
            for c in SENSE for r in hit.get(c, [])[:MAX_GLOSS_PER_SOURCE]]

# ---- Sanskrit synonym koshas (Sanskrit-side corroboration, Rule 5) -----------
# Non-Cologne indic-dict koshas (Amarakosha etc.), built by build_kosha.py. They
# fill `skd_vcp_synonyms`: Sanskrit synonyms that corroborate WHICH sense a PWG
# headword carries. NEVER Russian, never a correctness verdict (like SKD/VCP).
_KOSHA_IDX = None
def load_kosha_index():
    global _KOSHA_IDX
    if _KOSHA_IDX is not None:
        return _KOSHA_IDX
    idx = defaultdict(set)
    path = os.path.join(HERE, 'kosha_syn.jsonl')
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                e = json.loads(line)
                k = form_key(e.get('slp1', ''))
                if k:
                    idx[k].update(e.get('syn_dev', []))
    _KOSHA_IDX = idx
    return idx

def lookup_synonyms(key1, key2=None, limit=12):
    kidx = load_kosha_index()
    syn = kidx.get(form_key(key1)) or (kidx.get(form_key(key2)) if key2 else None) or set()
    return sorted(syn)[:limit]

# ---- Meulenbeld plant → Latin binomial (SNP) --------------------------------
_PLANT_IDX = None
def load_plant_index():
    global _PLANT_IDX
    if _PLANT_IDX is not None:
        return _PLANT_IDX
    idx = {}
    path = os.path.join(HERE, 'meulenbeld_plants.jsonl')
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                e = json.loads(line)
                for k in {form_key(e.get('slp1', '')), form_key(e.get('stem', ''))}:
                    if k and e.get('binomials'):
                        idx.setdefault(k, e['binomials'])
    _PLANT_IDX = idx
    return idx

def lookup_binomials(key1, key2=None):
    pidx = load_plant_index()
    return pidx.get(form_key(key1)) or (pidx.get(form_key(key2)) if key2 else None) or []

# ---- corpus query (reuse SamudraManthanam, read-only) --------------------
def corpus_connection():
    global _CORPUS_CON
    if _CORPUS_CON is None and os.path.exists(CORPUS_DB):
        _CORPUS_CON = sqlite3.connect('file:%s?mode=ro' % CORPUS_DB, uri=True)
    return _CORPUS_CON


def close_corpus_connection():
    global _CORPUS_CON
    if _CORPUS_CON is not None:
        _CORPUS_CON.close()
        _CORPUS_CON = None


atexit.register(close_corpus_connection)


def corpus_examples_with_status(slp1, limit=3):
    """Query aligned corpus verses, returning (examples, status). status is one of:
      'ok'                — the query RAN; [] then genuinely means no aligned verse
      'db_absent'         — the corpus DB file isn't present (evidence not available)
      'db_error'          — the DB is present but the query raised (evidence NOT
                            confirmed empty — a failure, not an absence of matches)
      'skipped_short_term'— the search term was <2 chars, deliberately not queried
    FL7: before this, every one of these returned a bare [] indistinguishable from
    'no matches', so a build/query failure silently read as 'word uncovered'."""
    if not os.path.exists(CORPUS_DB):
        return [], 'db_absent'
    term = slp1_to_ascii(slp1)
    if len(term) < 2:
        return [], 'skipped_short_term'
    out = []
    try:
        con = corpus_connection()
        # NB: corpus_lines also holds dictionary rows (no #sa/#ru suffix); filter
        # to Sanskrit verse lines in SQL so LIMIT captures verses, not dict rows
        # (otherwise common headwords return 0 — the first 400 matches are dicts).
        rows = con.execute(
            "SELECT canonical_id, line_text FROM corpus_lines "
            "WHERE corpus_lines MATCH ? AND canonical_id LIKE '%#sa' LIMIT 400",
            ('"%s"' % term,))
        for cid, _ in rows:
            if not cid or not cid.endswith('#sa'):
                continue
            grp = cid[:-3]
            ru = con.execute(
                "SELECT line_text FROM corpus_lines WHERE canonical_id = ? LIMIT 1",
                (grp + '#ru',)).fetchone()
            if ru and ru[0]:
                work, _, passage = grp.partition(':')
                out.append({'work': work, 'passage': passage, 'ru': ru[0]})
                if len(out) >= limit:
                    break
    except Exception as ex:
        sys.stderr.write('corpus query FAILED (evidence NOT confirmed empty): %s\n' % ex)
        return out, 'db_error'
    return out, 'ok'


def corpus_examples(slp1, limit=3):
    """Back-compatible list-only wrapper (see corpus_examples_with_status)."""
    return corpus_examples_with_status(slp1, limit)[0]

# ---- heuristic correctness pre-check (LLM is the real verdict) -----------
_RU_END = re.compile(r'(ого|ому|ыми|ами|ого|ая|ое|ые|ый|ий|ом|ой|ах|ам|ов|у|ю|и|ы|а|я|о|е|ь|й|х|м)$')
# Excel formula-error strings (Russian locale) that leaked into a handful of
# gate-source builds (e.g. `#ИМЯ?` = "#NAME?", found in fri/smirnov, H409).
# These are NOT Russian prose; strip before tokenizing so a real word embedded
# in the error marker (`ИМЯ` = "name") doesn't get counted as a usable gloss.
_SPREADSHEET_ERR_RE = re.compile(r'#(?:ИМЯ|ЗНАЧ|ССЫЛКА|ДЕЛ/0|ПУСТО|ЧИСЛО|Н/Д)\?')


def ru_has_content(tok):
    """True if a single lowercase Cyrillic token carries real meaning, using a
    RELAXED floor: a token that is ALREADY <=3 letters before stemming is a
    short closed-class word in its own right (pronoun/particle: `она`, `оно`,
    `это`, `все`, `кто`, `что`, ...) — case-stemming a 3-letter word routinely
    strips it below the >=3-after-stemming floor (e.g. `оно` -> `он`, 2 chars,
    discarded) even though the whole word is meaningful (H409).

    NOT used by `ru_tokens`/`annotate_evidence.ru_tokens_full` — those feed
    `best_relation`'s token-containment RATIO (`|a∩b| / |a|`), where adding a
    grammatical connector like `что` (as in `что-либо` = "something") to the
    denominator dilutes the ratio and flips previously-correct `supports`
    verdicts to none (measured: 107 lost vs 37 gained on the live store — a
    net regression, not an improvement). This relaxed floor is for boolean
    PRESENCE checks only (`koch_xref.has_meaning` / `is_bare_xref`), where a
    false positive on a function word is low-stakes (a gloss containing `что`
    is essentially never a bare cross-reference to begin with). Two different
    consumers, two different risk profiles — do not unify them."""
    if len(tok) <= 3:
        return len(tok) >= 3
    return len(_RU_END.sub('', tok)) >= 3


def ru_tokens(text):
    if HEAD_SENSE_ONLY:
        text = text.split(';')[0]
    text = re.sub(r'\{T\d+\}', ' ', text)          # drop placeholders
    text = re.sub(r'<[^>]+>', ' ', text)           # drop markup
    text = _SPREADSHEET_ERR_RE.sub(' ', text)      # drop leaked Excel error strings
    toks = re.findall(r'[а-яёА-ЯЁ]{2,}', text.lower())
    return {_RU_END.sub('', t) for t in toks if len(_RU_END.sub('', t)) >= 3}

def heuristic(pwg_ru, indep):
    """Cheap PRE-check, NOT the verdict. Returns one of:
      no-check  — no independent gloss for the key
      pass      — high head-term overlap; a confident auto-accept
      review    — has a gloss but low overlap → send to the LLM (4_korpus),
                  which is synonym-aware and is the only thing that may say
                  'divergence'. (Tuning showed low overlap is the norm even
                  between agreeing human dictionaries.)"""
    if not indep:
        return 'no-check', 0.0
    a = ru_tokens(pwg_ru)
    if not a:
        return 'no-check', 0.0
    best = 0.0
    for g in indep:
        b = ru_tokens(g['gloss'])
        if b:
            best = max(best, len(a & b) / len(a))
    return ('pass' if best >= THRESHOLD else 'review'), round(best, 2)


def deterministic_precheck(pwg_ru, indep):
    status, score = heuristic(pwg_ru, indep)
    if status == 'pass':
        route = 'auto-pass-deterministic'
        note = 'high head-term overlap with an independent Sanskrit-Russian gloss'
    elif status == 'review':
        route = 'llm-verdict-required'
        note = 'independent evidence exists, but synonym-aware LLM verdict is required'
    else:
        route = 'llm-verdict-required'
        note = 'no usable independent Russian gloss for a deterministic precheck'
    return {'status': status, 'route': route, 'score': score,
            'threshold': THRESHOLD, 'head_sense_only': HEAD_SENSE_ONLY,
            'note': note}

def build_card(idx, key1, key2, pwg_ru):
    indep, kow = lookup(idx, key1, key2)
    corpus_ex, corpus_stat = corpus_examples_with_status(key1)
    return {'key1': key1, 'key2': key2 or key1, 'pwg_ru': pwg_ru,
            'independent_glosses': [{'source': g['source'], 'code': g['code'],
                                     'gloss': g['gloss']} for g in indep],
            'kow_reference': kow,
            'specialist_glosses': lookup_specialist(key1, key2),  # text-specific name glossaries, evidence-only
            'deterministic_precheck': deterministic_precheck(pwg_ru, indep),
            # FL7 markers: distinguish "evidence not built/available" from
            # "consulted and empty" so the LLM verdict prompt never mistakes a
            # missing source for an uncovered headword.
            'evidence_status': evidence_status(),
            'hindi_sense': lookup_sense(key1, key2),   # soft sense signal, not correctness
            'corpus_examples': corpus_ex,
            'corpus_status': corpus_stat,
            'latin_binomials': lookup_binomials(key1, key2),   # Meulenbeld/SNP, botanical
            'skd_vcp_synonyms': lookup_synonyms(key1, key2)}   # Sanskrit kosha synonyms

# ---- CLI -----------------------------------------------------------------
def read_keys(limit=None):
    with open(PWG_KEY1, encoding='utf-8') as f:
        for i, line in enumerate(f):
            if limit and i >= limit:
                break
            k = line.strip()
            if k:
                yield k

def cmd_lookup(idx, args):
    key1 = args[0]; key2 = args[1] if len(args) > 1 else None
    indep, kow = lookup(idx, key1, key2)
    print('PWG headword: %s (form_key %s)' % (key1, form_key(key1)))
    print('IAST: %s | search: %s' % (''.join(_S2I.get(c, c) for c in form_key(key1)), slp1_to_ascii(key1)))
    print('\nindependent glosses (%d):' % len(indep))
    for g in indep:
        print('  [%s] %s' % (g['source'], g['gloss'][:160]))
    print('\nKOW reference (%d):' % len(kow))
    for g in kow:
        print('  %s' % g[:160])
    spec = lookup_specialist(key1, key2)
    print('\nspecialist name-glossaries (%d) — evidence-only, text-specific:' % len(spec))
    for g in spec:
        print('  [%s] %s' % (g['source'], g['gloss'][:160]))
    sense = lookup_sense(key1, key2)
    print('\nHindi sense signal (%d) — soft, sense-disambiguation only:' % len(sense))
    for s in sense:
        print('  [%s %s] %s' % (s['source'], s['pos'], s['gloss'][:140]))
    syn = lookup_synonyms(key1, key2)
    print('\nSanskrit kosha synonyms (%d) — Sanskrit-side corroboration:' % len(syn))
    if syn:
        print('  ' + ', '.join(syn))
    binom = lookup_binomials(key1, key2)
    if binom:
        print('\nLatin binomials (Meulenbeld/SNP): ' + '; '.join(binom))
    ex = corpus_examples(key1, 3)
    print('\ncorpus examples (%d):' % len(ex))
    for e in ex:
        print('  %s %s — %s' % (e['work'], e['passage'], e['ru'][:140]))

def cmd_card(idx, args):
    print(json.dumps(build_card(idx, args[0], None, args[1]), ensure_ascii=False, indent=2))

COVERAGE_SEED = 20260615   # fixed seed → reproducible random samples

def cmd_coverage(idx, args):
    n = int(args[0]) if args else None
    rng = random.Random(COVERAGE_SEED)
    all_keys = [k for k in read_keys(None)]
    total = len(all_keys)
    # RANDOM sample, not first-N: PWG keys are SLP1-sorted and the a- section is
    # over-covered (esp. KOW), so a first-N slice badly overstates coverage.
    if n and n < total:
        keys = rng.sample(all_keys, n)
        label = 'random sample %d / %d (seed %d)' % (n, total, COVERAGE_SEED)
    else:
        keys = all_keys
        label = 'full %d' % total
    # KOW (Kossovich) is alphabetically INCOMPLETE — its headwords start with
    # only a handful of SLP1 letters (WIL-seeded, scattered). Coverage averaged
    # over the whole alphabet dilutes its real density: outside its letter-zone
    # KOW is absent by construction, not because a headword is missing. So report
    # KOW both overall and WITHIN its attested zone.
    kow_zone = set(k[0] for k, h in idx.items() if REF in h and k)
    sidx = load_sense_index()
    kidx = load_kosha_index()
    pidx = load_plant_index()
    tot = per = kow_n = kow_zone_n = sense_n = syn_n = plant_n = 0
    persrc = defaultdict(int)
    sensesrc = defaultdict(int)
    for k in keys:
        tot += 1
        fk = form_key(k)
        hit = idx.get(fk) or {}
        if any(c in hit for c in INDEP):
            per += 1
        for c in INDEP:
            if c in hit:
                persrc[c] += 1
        if REF in hit:
            kow_n += 1
        if fk and fk[0] in kow_zone:
            kow_zone_n += 1
        shit = sidx.get(fk) or {}
        if shit:
            sense_n += 1
        for c in SENSE:
            if c in shit:
                sensesrc[c] += 1
        if fk in kidx:
            syn_n += 1
        if fk in pidx:
            plant_n += 1
    # corpus signal: its own random sub-sample of the scanned keys (the corpus
    # query is the slow part, so it stays capped) — representative, not first-300.
    corpus_n = min(300, len(keys))
    corp_keys = rng.sample(keys, corpus_n)
    corp_hit = sum(1 for k in corp_keys if corpus_examples(k, 1))
    print('PWG headwords scanned: %d (%s)' % (tot, label))
    print('--- signal 1: correctness coverage (any independent dict) ---')
    print('  covered: %d (%.1f%%)' % (per, 100.0 * per / tot))
    for c in INDEP:
        print('    %-8s %6d (%.1f%%)' % (NAME[c], persrc[c], 100.0 * persrc[c] / tot))
    print('--- signal 2: reference coverage (KOW) ---')
    print('  KOW over all PWG:   %d (%.1f%%)' % (kow_n, 100.0 * kow_n / tot))
    print('  KOW within its letter-zone [%s]: %d / %d (%.1f%%) — zone = %.1f%% of scanned;'
          % (''.join(sorted(kow_zone)), kow_n, kow_zone_n,
             100.0 * kow_n / max(kow_zone_n, 1), 100.0 * kow_zone_n / tot))
    print('    outside the zone KOW is absent by construction, not a missing entry.')
    print('--- corpus signal (random sample of %d): %d had >=1 aligned verse (%.1f%%)'
          % (corpus_n, corp_hit, 100.0 * corp_hit / max(corpus_n, 1)))
    print('--- Hindi SENSE signal (soft, third-language; not correctness) ---')
    print('  any Hindi gloss: %d (%.1f%%)' % (sense_n, 100.0 * sense_n / tot))
    for c in SENSE:
        print('    %-22s %6d (%.1f%%)' % (SENSE_NAME[c], sensesrc[c], 100.0 * sensesrc[c] / tot))
    print('--- Sanskrit kosha synonyms (Sanskrit-side corroboration, Rule 5) ---')
    print('  kosha synonym set: %d (%.1f%%)' % (syn_n, 100.0 * syn_n / tot))
    print('--- Meulenbeld/SNP Latin binomials (botanical) ---')
    print('  plant w/ binomial: %d (%.1f%%)' % (plant_n, 100.0 * plant_n / tot))

def cmd_tune(idx, args):
    """Inter-dictionary agreement: for headwords covered by >=2 independent
    dicts, the head-term token Jaccard distribution — calibrates THRESHOLD."""
    n = int(args[0]) if args else 4000
    rng = random.Random(COVERAGE_SEED)
    all_keys = [k for k in read_keys(None)]
    total = len(all_keys)
    # RANDOM sample, not first-N (PWG is SLP1-sorted; the a- section is skewed).
    if n and n < total:
        keys = rng.sample(all_keys, n)
        label = 'random sample %d / %d (seed %d)' % (n, total, COVERAGE_SEED)
    else:
        keys = all_keys
        label = 'full %d' % total
    buckets = defaultdict(int); pairs = 0
    for k in keys:
        hit = idx.get(form_key(k)) or {}
        present = [c for c in INDEP if hit.get(c)]
        if len(present) < 2:
            continue
        sets = [ru_tokens(hit[c][0]) for c in present]
        for i in range(len(sets)):
            for j in range(i + 1, len(sets)):
                a, b = sets[i], sets[j]
                if not a or not b:
                    continue
                ov = len(a & b) / len(a | b)
                pairs += 1
                buckets[min(int(ov * 10) / 10, 0.9)] += 1
    print('inter-dictionary head-term agreement over %d headwords [%s] (%d dict pairs):'
          % (len(keys), label, pairs))
    cum = 0
    for b in sorted(buckets, reverse=True):
        cum += buckets[b]
        print('  Jaccard >= %.1f : %5d pairs  (%.1f%% cumulative)'
              % (b, buckets[b], 100.0 * cum / max(pairs, 1)))
    print('\nTHRESHOLD=%.2f (current) — head-term overlap above this counts as agreement.' % THRESHOLD)

def main():
    if len(sys.argv) < 2:
        print(__doc__); return
    idx = load_index()
    cmd, args = sys.argv[1], sys.argv[2:]
    {'lookup': cmd_lookup, 'card': cmd_card,
     'coverage': cmd_coverage, 'tune': cmd_tune}.get(cmd, lambda *_: print(__doc__))(idx, args)

if __name__ == '__main__':
    main()
