#!/usr/bin/env python
"""pwg_ru stage-4 corpus gate — deterministic join + corpus query.

Joins a PWG headword (SLP1 key) to the five extracted Sanskrit→Russian
dictionaries in this directory and (optionally) to the SamudraManthanam
verse-aligned parallel corpus, assembling the input the LLM verdict prompt
(pwg_ru_prompts/4_korpus_proverka.txt) consumes. It also offers a cheap,
tunable heuristic correctness pre-check (the LLM is the real verdict).

This is CODE (committed); the dictionary data it reads (src/*.jsonl) is
gitignored and regenerated by build_src.py. The corpus query REUSES
SamudraManthanam's corpus.db (read-only) — it does not duplicate the corpus.

Modes:
  python corpus_gate.py lookup  <key1> [key2]      one headword → glosses + examples
  python corpus_gate.py card    <key1> "<pwg_ru>"  emit the 4_korpus input JSON
  python corpus_gate.py coverage [N]               per-signal coverage over PWG
  python corpus_gate.py tune     [N]               inter-dictionary agreement → threshold
"""
import json, os, re, sys, sqlite3, unicodedata
from collections import defaultdict

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
GITHUB = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
PWG_KEY1 = os.path.join(HERE, '..', '..', 'HeadwordLists', 'PWG-unique-key1-106085.txt')
CORPUS_DB = os.environ.get('SAMUDRA_CORPUS_DB',
                           os.path.join(GITHUB, 'SamudraManthanam', 'web', 'corpus.db'))

# ---- tunables ------------------------------------------------------------
# THRESHOLD tuned by `tune` (inter-dictionary agreement): two independent human
# dictionaries share head-term tokens only at LOW overlap (synonyms/paraphrase),
# so a high bar is a confident auto-PASS, but anything below is routed to the LLM
# (4_korpus_proverka.txt) — it is NOT auto-divergence. Only the LLM declares
# 'divergence'. 0.5 = at least half the pwg_ru head tokens appear in one gloss.
THRESHOLD = 0.5
HEAD_SENSE_ONLY = True     # compare only sense 1 (text before the first ';')
MAX_GLOSS_PER_SOURCE = 4   # cap glosses fed per source
# --------------------------------------------------------------------------

INDEP = ['koch', 'kna', 'fri', 'smirnov']   # independent correctness authorities
REF = 'kow'                                  # WIL-seeded human PWG→RU reference
NAME = {'koch': 'Кочергина', 'kna': 'Кнауэр', 'fri': 'Фриш',
        'smirnov': 'Смирнов', 'kow': 'Коссович'}

# SLP1 -> IAST (for corpus search / display)
_S2I = {'A':'ā','I':'ī','U':'ū','f':'ṛ','F':'ṝ','x':'ḷ','X':'ḹ','E':'ai','O':'au',
        'M':'ṃ','H':'ḥ','N':'ṅ','Y':'ñ','w':'ṭ','W':'ṭh','q':'ḍ','Q':'ḍh','R':'ṇ',
        'S':'ś','z':'ṣ','K':'kh','G':'gh','C':'ch','J':'jh','T':'th','D':'dh',
        'P':'ph','B':'bh'}

def form_key(s):
    """Length-preserving SLP1 normalization for joining (keeps case/length;
    drops accents, slashes, hyphen bounds — NOT a naive NFD-strip-Mn)."""
    if not s:
        return ''
    s = unicodedata.normalize('NFC', s.strip())
    s = re.sub(r'[̀-ͯ]', '', s)
    s = s.replace('/', '').replace('\\', '').replace('|', '').replace(' ', '')
    return s.strip('-')

def slp1_to_ascii(s):
    """SLP1 -> diacritic-free lowercase roman, for FTS search."""
    iast = ''.join(_S2I.get(c, c) for c in form_key(s))
    nfd = unicodedata.normalize('NFD', iast)
    return ''.join(c for c in nfd if not unicodedata.combining(c)).lower()

# ---- dictionary index ----------------------------------------------------
def load_index():
    idx = defaultdict(lambda: defaultdict(list))
    for code in INDEP + [REF]:
        path = os.path.join(HERE, code + '.jsonl')
        if not os.path.exists(path):
            continue
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                e = json.loads(line)
                k = form_key(e.get('slp1', ''))
                if k:
                    idx[k][code].append(e.get('gloss', ''))
    return idx

def lookup(idx, key1, key2=None):
    hit = idx.get(form_key(key1))
    if not hit and key2:
        hit = idx.get(form_key(key2))
    hit = hit or {}
    indep = [{'source': NAME[c], 'code': c, 'gloss': g}
             for c in INDEP for g in hit.get(c, [])[:MAX_GLOSS_PER_SOURCE]]
    kow = hit.get(REF, [])[:MAX_GLOSS_PER_SOURCE]
    return indep, kow

# ---- corpus query (reuse SamudraManthanam, read-only) --------------------
def corpus_examples(slp1, limit=3):
    if not os.path.exists(CORPUS_DB):
        return []
    term = slp1_to_ascii(slp1)
    if len(term) < 2:
        return []
    out = []
    try:
        con = sqlite3.connect('file:%s?mode=ro' % CORPUS_DB, uri=True)
        rows = con.execute(
            "SELECT canonical_id, line_text FROM corpus_lines "
            "WHERE corpus_lines MATCH ? LIMIT 400", ('"%s"' % term,))
        for cid, _ in rows:
            if not cid or not cid.endswith('#sa'):
                continue
            grp = cid[:-3]
            ru = con.execute(
                "SELECT line_text FROM corpus_lines WHERE canonical_id = ? LIMIT 1",
                (grp + '#ru',)).fetchone()
            if ru and ru[0]:
                work, _, passage = grp.partition(':')
                out.append({'work': work, 'passage': passage, 'ru': ru[0]})
                if len(out) >= limit:
                    break
        con.close()
    except Exception as ex:
        sys.stderr.write('corpus query skipped: %s\n' % ex)
    return out

# ---- heuristic correctness pre-check (LLM is the real verdict) -----------
_RU_END = re.compile(r'(ого|ому|ыми|ами|ого|ая|ое|ые|ый|ий|ом|ой|ах|ам|ов|у|ю|и|ы|а|я|о|е|ь|й|х|м)$')
def ru_tokens(text):
    if HEAD_SENSE_ONLY:
        text = text.split(';')[0]
    text = re.sub(r'\{T\d+\}', ' ', text)          # drop placeholders
    text = re.sub(r'<[^>]+>', ' ', text)           # drop markup
    toks = re.findall(r'[а-яёА-ЯЁ]{2,}', text.lower())
    return {_RU_END.sub('', t) for t in toks if len(_RU_END.sub('', t)) >= 3}

def heuristic(pwg_ru, indep):
    """Cheap PRE-check, NOT the verdict. Returns one of:
      no-check  — no independent gloss for the key
      pass      — high head-term overlap; a confident auto-accept
      review    — has a gloss but low overlap → send to the LLM (4_korpus),
                  which is synonym-aware and is the only thing that may say
                  'divergence'. (Tuning showed low overlap is the norm even
                  between agreeing human dictionaries.)"""
    if not indep:
        return 'no-check', 0.0
    a = ru_tokens(pwg_ru)
    if not a:
        return 'no-check', 0.0
    best = 0.0
    for g in indep:
        b = ru_tokens(g['gloss'])
        if b:
            best = max(best, len(a & b) / len(a))
    return ('pass' if best >= THRESHOLD else 'review'), round(best, 2)

def build_card(idx, key1, key2, pwg_ru):
    indep, kow = lookup(idx, key1, key2)
    return {'key1': key1, 'key2': key2 or key1, 'pwg_ru': pwg_ru,
            'independent_glosses': [{'source': g['source'], 'code': g['code'],
                                     'gloss': g['gloss']} for g in indep],
            'kow_reference': kow,
            'corpus_examples': corpus_examples(key1),
            'skd_vcp_synonyms': []}

# ---- CLI -----------------------------------------------------------------
def read_keys(limit=None):
    with open(PWG_KEY1, encoding='utf-8') as f:
        for i, line in enumerate(f):
            if limit and i >= limit:
                break
            k = line.strip()
            if k:
                yield k

def cmd_lookup(idx, args):
    key1 = args[0]; key2 = args[1] if len(args) > 1 else None
    indep, kow = lookup(idx, key1, key2)
    print('PWG headword: %s (form_key %s)' % (key1, form_key(key1)))
    print('IAST: %s | search: %s' % (''.join(_S2I.get(c, c) for c in form_key(key1)), slp1_to_ascii(key1)))
    print('\nindependent glosses (%d):' % len(indep))
    for g in indep:
        print('  [%s] %s' % (g['source'], g['gloss'][:160]))
    print('\nKOW reference (%d):' % len(kow))
    for g in kow:
        print('  %s' % g[:160])
    ex = corpus_examples(key1, 3)
    print('\ncorpus examples (%d):' % len(ex))
    for e in ex:
        print('  %s %s — %s' % (e['work'], e['passage'], e['ru'][:140]))

def cmd_card(idx, args):
    print(json.dumps(build_card(idx, args[0], None, args[1]), ensure_ascii=False, indent=2))

def cmd_coverage(idx, args):
    n = int(args[0]) if args else None
    corpus_sample = 300
    tot = per = kow_n = corp_hit = corp_seen = 0
    persrc = defaultdict(int)
    for k in read_keys(n):
        tot += 1
        hit = idx.get(form_key(k)) or {}
        if any(c in hit for c in INDEP):
            per += 1
        for c in INDEP:
            if c in hit:
                persrc[c] += 1
        if REF in hit:
            kow_n += 1
        if corp_seen < corpus_sample:
            corp_seen += 1
            if corpus_examples(k, 1):
                corp_hit += 1
    print('PWG headwords scanned: %d' % tot)
    print('--- signal 1: correctness coverage (any independent dict) ---')
    print('  covered: %d (%.1f%%)' % (per, 100.0 * per / tot))
    for c in INDEP:
        print('    %-8s %6d (%.1f%%)' % (NAME[c], persrc[c], 100.0 * persrc[c] / tot))
    print('--- signal 2: reference coverage (KOW) ---')
    print('  KOW: %d (%.1f%%)' % (kow_n, 100.0 * kow_n / tot))
    print('--- corpus signal (sample of %d): %d had >=1 aligned verse (%.1f%%)'
          % (corp_seen, corp_hit, 100.0 * corp_hit / max(corp_seen, 1)))

def cmd_tune(idx, args):
    """Inter-dictionary agreement: for headwords covered by >=2 independent
    dicts, the head-term token Jaccard distribution — calibrates THRESHOLD."""
    n = int(args[0]) if args else 4000
    buckets = defaultdict(int); pairs = 0
    for k in read_keys(n):
        hit = idx.get(form_key(k)) or {}
        present = [c for c in INDEP if hit.get(c)]
        if len(present) < 2:
            continue
        sets = [ru_tokens(hit[c][0]) for c in present]
        for i in range(len(sets)):
            for j in range(i + 1, len(sets)):
                a, b = sets[i], sets[j]
                if not a or not b:
                    continue
                ov = len(a & b) / len(a | b)
                pairs += 1
                buckets[min(int(ov * 10) / 10, 0.9)] += 1
    print('inter-dictionary head-term agreement over %d headwords (%d dict pairs):' % (n, pairs))
    cum = 0
    for b in sorted(buckets, reverse=True):
        cum += buckets[b]
        print('  Jaccard >= %.1f : %5d pairs  (%.1f%% cumulative)'
              % (b, buckets[b], 100.0 * cum / max(pairs, 1)))
    print('\nTHRESHOLD=%.2f (current) — head-term overlap above this counts as agreement.' % THRESHOLD)

def main():
    if len(sys.argv) < 2:
        print(__doc__); return
    idx = load_index()
    cmd, args = sys.argv[1], sys.argv[2:]
    {'lookup': cmd_lookup, 'card': cmd_card,
     'coverage': cmd_coverage, 'tune': cmd_tune}.get(cmd, lambda *_: print(__doc__))(idx, args)

if __name__ == '__main__':
    main()
