#!/usr/bin/env python
r"""H3751 fold -- census (and evidence-decidable repair) of degraded `key1` (issue #1767).

Issue #1767: the canonical store's `key1` is a flattened lemma form on ~161 rows (`apta`
for `Apta`, `gawa` for `Gawa`, `asru` for `aSru`), three keys conflate distinct lemmas
(`vasa` = vAsA/vAsa/vaSA/vaSa/vasA), and one row carries sub-card junk in `key1`. The
issue also names the witness: **the sub-card prefix before `~~`** -- 11,442 of 11,603 rows
agreed with `key1`, and every disagreement resolved in the sub-card's favour.

This censuses that disagreement against the PWG source and splits it into:

  decidable_subcard_only  the sub-card witness IS a PWG headword and `key1` is NOT --
                          the flattened form names no entry, the witness names one.
                          Evidence-decidable: repair `key1` to the witness.
  ambiguous_both_real     both spellings are real PWG headwords. Which word the card
                          translates is then a lexicographic reading of the German text,
                          not a mechanical join; reported, never repaired here.
  ambiguous_neither       neither spelling is in PWG (wrong-entry ingest, upstream
                          fetch defect); H2996's quarantine lane owns these.
  witness_absent          no `~~` in the sub-card, so there is no independent witness.

    python src/h3751_key1_census.py [--json OUT] [--report OUT.md]
    python src/h3751_key1_census.py --apply --ledger reports/H3751_key1_ledger.jsonl

`--apply` repairs ONLY the `decidable_subcard_only` class, one JSONL ledger row per change,
under the H2146 store lock; `iast` is recomputed from the repaired key so the two cannot
disagree. Everything else lands in the report, per the handoff's "repair only what is
evidence-decidable, ledgered; the rest lands in the report".
"""
import argparse
import collections
import io
import json
import os
import sys
import time

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import corpus_gate as cg                                              # noqa: E402
from pwg_homonym import index_by_form_key, split_subcard              # noqa: E402
from pwg_page_index import DEFAULT_SRC, parse_source                  # noqa: E402
from store_path import canonical_store                                # noqa: E402
from store_write import locked_store_rewrite                          # noqa: E402

DEFAULT_STORE = canonical_store(os.path.join(HERE, 'pwg_ru_translated.jsonl'))
DEFAULT_LEDGER = os.path.normpath(os.path.join(HERE, '..', 'reports',
                                               'H3751_key1_ledger.jsonl'))
SCHEMA = 'pwg_ru.h3751_key1_repair.v1'


def load_rows(path):
    with io.open(path, encoding='utf-8') as f:
        return [json.loads(line) for line in f if line.strip()]


def iast_of(key):
    """The store's own SLP1 -> IAST rendering, as `_pilot_gen_merged.subcard_portrait` does."""
    return ''.join(cg._S2I.get(c, c) for c in cg.form_key(key))


def census(rows, by_fk):
    findings = collections.defaultdict(list)
    for i, r in enumerate(rows):
        subcard = r.get('subcard') or ''
        witness, _ = split_subcard(subcard)
        key1 = r.get('key1') or ''
        if not witness or witness == key1:
            continue
        if '~~' not in subcard:
            findings['witness_absent'].append((i, key1, witness, r))
            continue
        key_real = bool(by_fk.get(cg.form_key(key1)))
        wit_real = bool(by_fk.get(cg.form_key(witness)))
        if wit_real and not key_real:
            findings['decidable_subcard_only'].append((i, key1, witness, r))
        elif wit_real and key_real:
            findings['ambiguous_both_real'].append((i, key1, witness, r))
        else:
            findings['ambiguous_neither'].append((i, key1, witness, r))
    return findings


def pair_counts(items):
    c = collections.Counter((key1, witness) for _, key1, witness, _ in items)
    return c.most_common()


def write_report(path, result):
    lines = [
        '# H3751 fold -- degraded `key1` census (#1767)',
        '',
        '_Created: 31-08-2026 · Last updated: 31-08-2026_',
        '',
        'Generated by [`src/h3751_key1_census.py`](https://github.com/gasyoun/SanskritLexicography/blob/master/RussianTranslation/src/h3751_key1_census.py). Store: '
        '%d rows; PWG source: %d records. The witness is the sub-card prefix before `~~`, '
        'per issue [#1767](https://github.com/gasyoun/SanskritLexicography/issues/1767).'
        % (result['store_rows'], result['source_records']),
        '',
        '## Verdict',
        '',
        ('**Zero** rows disagree with their sub-card witness, so nothing in this class is '
         'evidence-decidable to repair -- there is nothing left to repair. The corroborating '
         'name-by-name lookup of the issue\'s own worked examples '
         '(`src/h3751_key1_probe.py`, report `H3751_KEY1_1767_PROBE_31-08-2026.json`) finds '
         'each of `apta` / `gawa` / `asru`, `vasa` / `bara` / `vasin`, the '
         '`durg_a~~h0_zz_sch` junk key and the degraded `gaṭa` / `manorata` IAST values '
         'absent from the store: H2996\'s wrong-entry quarantine and the in-place key '
         'repairs that followed already closed #1767. This census is the regression guard, '
         'not a repair pass -- it reads the gitignored live store, so it is an operator '
         'check rather than a CI job.'
         if not any(result['classes'].values()) else
         '%d row(s) disagree with their sub-card witness; see the class table below for '
         'what is repairable.' % sum(result['classes'].values())),
        '',
        '## Classes',
        '',
        '| Class | Rows | Repaired here |',
        '|---|---|---|',
    ]
    repairable = {'decidable_subcard_only'}
    for cls in ('decidable_subcard_only', 'ambiguous_both_real', 'ambiguous_neither',
                'witness_absent'):
        lines.append('| `%s` | %d | %s |'
                     % (cls, result['classes'].get(cls, 0),
                        'yes' if cls in repairable else 'no -- reported only'))
    for cls in ('decidable_subcard_only', 'ambiguous_both_real', 'ambiguous_neither'):
        pairs = result['pairs'].get(cls) or []
        if not pairs:
            continue
        lines += ['', '### `%s`' % cls, '', '| stored `key1` | sub-card witness | rows |',
                  '|---|---|---|']
        for (key1, witness), n in pairs[:60]:
            lines.append('| `%s` | `%s` | %d |' % (key1, witness, n))
        if len(pairs) > 60:
            lines.append('| … %d more pairs | | |' % (len(pairs) - 60))
    lines += ['', '## What is deliberately NOT repaired', '',
              '1. `ambiguous_both_real` -- both spellings name a real PWG entry, so which '
              'word the card translates is a reading of its German text, not a join. '
              'Issue #1767\'s `vasa` / `bara` / `vasin` conflations are this class.',
              '2. `ambiguous_neither` -- neither spelling is in PWG at all; that is the '
              'wrong-entry ingest class H2996 quarantined, not a key-spelling defect.',
              '3. `witness_absent` -- a whole-card row carries no `~~` witness, so nothing '
              'independent contradicts its `key1`.', '',
              '_Dr. Mārcis Gasūns_', '']
    with io.open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--store', default=DEFAULT_STORE)
    ap.add_argument('--src', default=DEFAULT_SRC)
    ap.add_argument('--json', default=None)
    ap.add_argument('--report', default=None)
    ap.add_argument('--ledger', default=DEFAULT_LEDGER)
    ap.add_argument('--apply', action='store_true',
                    help='repair the decidable class in place, ledgered')
    args = ap.parse_args()

    entries = parse_source(args.src)
    by_fk = index_by_form_key(entries)
    rows = load_rows(args.store)
    findings = census(rows, by_fk)
    classes = {k: len(v) for k, v in findings.items()}
    print('store rows=%d source records=%d' % (len(rows), len(entries)))
    for k in sorted(classes):
        print('  %-28s %5d' % (k, classes[k]))

    result = {'store': args.store, 'store_rows': len(rows), 'source_records': len(entries),
              'classes': classes,
              'pairs': {k: pair_counts(v) for k, v in findings.items()}}
    if args.json:
        with io.open(args.json, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(result, f, ensure_ascii=False, indent=1)
        print('wrote %s' % args.json)
    if args.report:
        write_report(args.report, result)
        print('wrote %s' % args.report)

    decidable = findings.get('decidable_subcard_only') or []
    if not args.apply:
        for i, key1, witness, r in decidable[:10]:
            print('  would repair L%-6d %-16s -> %s' % (i + 1, key1, witness))
        print('DRY RUN -- %d repairable row(s); re-run with --apply to write.'
              % len(decidable))
        return 0
    if not decidable:
        print('nothing evidence-decidable to repair.')
        return 0

    ts = time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())
    ledger = []
    for i, key1, witness, r in decidable:
        before = {'key1': r.get('key1'), 'iast': r.get('iast')}
        r['key1'] = witness
        r['iast'] = iast_of(witness)
        ledger.append({'schema': SCHEMA, 'handoff': 'H3751', 'issue': 1767, 'ts': ts,
                       'line': i + 1, 'subcard': r.get('subcard'),
                       'sense_tag': r.get('sense_tag'),
                       'rule': 'sub-card witness is a PWG headword, stored key1 is not',
                       'changed': {'key1': {'old': before['key1'], 'new': r['key1']},
                                   'iast': {'old': before['iast'], 'new': r['iast']}}})
    bak = locked_store_rewrite(args.store, rows, tag='h3751k1')
    print('rewrote %s (backup: %s)' % (args.store, bak))
    os.makedirs(os.path.dirname(args.ledger), exist_ok=True)
    with io.open(args.ledger, 'w', encoding='utf-8', newline='\n') as f:
        for row in ledger:
            f.write(json.dumps(row, ensure_ascii=False) + '\n')
    print('wrote ledger %s (%d rows)' % (args.ledger, len(ledger)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
