#!/usr/bin/env python3
"""NKRYa evidence card for candidate Russian renderings (H5261).

Advisory only (grill 22-09-2026, ruling 3): the card shows the corpus facts, a human
votes, nothing is applied. For every (head noun, candidate) pair it records

  - where the candidate sits in the head's word sketch: every relation whose top-10
    lists it, with rank and dice (the API returns only the top 10 per relation, so
    "not in top 10" is the honest reading of an absence, never "unattested");
  - the candidate's own frequency: ipm and the NKRYa 1..6 category;
  - the pair count in MAIN (candidate lemma within 3 words of the head lemma, either
    order) with 3 concordance lines, and the same count in the 19th-century slice.

Candidates are given as `surface=lemma:POS`; NKRYa lemmatizes participles to their
verb, so «сгущающийся» is queried as `сгущающийся=сгущаться:V`.

  python src/nkrya_evidence_card.py --id C07 --heads туча:S,облако:S \\
      --candidates связный:A,последовательный:A,сплочённый:A,сплошной:A,\\
сгущающийся=сгущаться:V,сомкнутый=сомкнуть:V \\
      --out pwg_ru/h5069/C07_NKRYA_EVIDENCE_CARD.md
  python src/nkrya_evidence_card.py --selftest
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import nkrya_client as nk  # noqa: E402

PAIR_DIST = (-3, 3)
CATEGORY = {1: "очень редкое", 2: "редкое", 3: "скорее низкая", 4: "скорее высокая",
            5: "распространённое", 6: "очень распространённое"}


def parse_items(spec):
    """'a:S,b=c:V' -> [(surface, lemma, pos)]."""
    out = []
    for item in [x.strip() for x in spec.split(",") if x.strip()]:
        left, _, pos = item.rpartition(":")
        if not left:
            left, pos = pos, None
        surface, _, lemma = left.partition("=")
        out.append((surface, lemma or surface, pos or None))
    return out


def gather(cli, heads, candidates, n=3):
    """All corpus facts for the card, as plain data (JSON-serialisable)."""
    data = {"heads": [], "candidates": []}
    sketches = {}
    for h_surface, h_lemma, h_pos in heads:
        sketches[h_lemma] = cli.sketch(h_lemma, h_pos)
        data["heads"].append({"lemma": h_lemma, "pos": h_pos,
                              "freq": cli.freq(h_lemma, h_pos),
                              "relations": {r: len(v) for r, v in sketches[h_lemma].items()}})
    for c_surface, c_lemma, c_pos in candidates:
        row = {"surface": c_surface, "lemma": c_lemma, "pos": c_pos,
               "freq": cli.freq(c_lemma, c_pos), "per_head": []}
        for h_surface, h_lemma, _ in heads:
            hits = []
            for rel, rows in sketches[h_lemma].items():
                rank, dice = nk.rank_in(rows, c_lemma)
                if rank:
                    hits.append({"relation": rel, "rank": rank, "dice": dice})
            main = cli.pair(c_lemma, h_lemma, n=n, dist=PAIR_DIST)
            c19 = cli.pair(c_lemma, h_lemma, n=1, dist=PAIR_DIST, slice_19c=True)
            row["per_head"].append({"head": h_lemma, "sketch": hits,
                                    "pair_main": main["hits"], "lines": main["lines"],
                                    "pair_19c": c19["hits"]})
        data["candidates"].append(row)
    data["cache_keys"] = sorted(set(cli.used_keys))
    return data


def fmt_freq(f):
    if f.get("ipm") is None:
        return "нет данных"
    return "%.2f ipm (кат. %s, %s)" % (f["ipm"], f.get("category"),
                                        CATEGORY.get(f.get("category"), "?"))


def render(card_id, german, current, data):
    L = ["# NKRYa evidence card — %s" % card_id, "",
         "_Generated by `src/nkrya_evidence_card.py` (H5261). Advisory: a human votes; "
         "nothing is applied from this card._", "",
         "- **German span:** %s" % german, "- **Current Russian:** %s" % current,
         "- **Corpus:** НКРЯ, основной корпус (MAIN); 19th-century slice = texts created "
         "1800–1899.",
         "- **Pair window:** the candidate lemma within %d words of the head lemma, "
         "either order." % PAIR_DIST[1], ""]
    L += ["## Heads", "", "| Head | Frequency | Sketch relations returned |", "|---|---|---|"]
    for h in data["heads"]:
        L.append("| %s | %s | %s |" % (h["lemma"], fmt_freq(h["freq"]),
                                       ", ".join("%s (%d)" % kv for kv in h["relations"].items())
                                       or "none"))
    L += ["", "## Candidates", "",
          "| Candidate | Frequency | Head | Sketch (relation, rank, dice) | Pair hits MAIN | "
          "Pair hits 19c |", "|---|---|---|---|---|---|"]
    for c in data["candidates"]:
        name = c["surface"] if c["surface"] == c["lemma"] else "%s (лемма %s)" % (
            c["surface"], c["lemma"])
        for i, ph in enumerate(c["per_head"]):
            sk = "; ".join("%s #%d, %.2f" % (s["relation"], s["rank"], s["dice"] or 0)
                           for s in ph["sketch"]) or "not in top 10"
            L.append("| %s | %s | %s | %s | %s | %s |" % (
                name if i == 0 else "", fmt_freq(c["freq"]) if i == 0 else "",
                ph["head"], sk, ph["pair_main"], ph["pair_19c"]))
    L += ["", "## Concordance lines (MAIN, up to 3 per pair)", ""]
    for c in data["candidates"]:
        for ph in c["per_head"]:
            L.append("**%s + %s**" % (c["lemma"], ph["head"]))
            L.append("")
            L += ["%d. %s" % (i, line) for i, line in enumerate(ph["lines"], 1)] or ["(no lines)"]
            L.append("")
    L += ["## Provenance", "",
          "Cache entries (committed under `pwg_ru/nkrya_cache/`): " +
          ", ".join("`%s`" % k for k in data["cache_keys"]), "", "_Гасунс_", ""]
    return "\n".join(L)


def selftest():
    fx = os.path.abspath(nk.FIXTURES)
    cli = nk.NkryaClient(cache_dir=fx, offline=True)
    assert parse_items("туча:S,сгущающийся=сгущаться:V") == [
        ("туча", "туча", "S"), ("сгущающийся", "сгущаться", "V")]
    # the fixture holds a sketch for «слово», so render one head/candidate on it
    sk = cli.sketch("слово", "S")
    hits = [{"relation": r, "rank": nk.rank_in(v, "добрый")[0],
             "dice": nk.rank_in(v, "добрый")[1]} for r, v in sk.items()
            if nk.rank_in(v, "добрый")[0]]
    assert hits == [{"relation": "amod_S_A", "rank": 4, "dice": 8.57147}], hits
    data = {"heads": [{"lemma": "слово", "pos": "S", "freq": {"ipm": None},
                       "relations": {"amod_S_A": 10}}],
            "candidates": [{"surface": "добрый", "lemma": "добрый", "pos": "A",
                            "freq": {"ipm": 44.0418, "category": 3},
                            "per_head": [{"head": "слово", "sketch": hits, "pair_main": 137,
                                          "lines": ["x [добрый] [слово]"], "pair_19c": 5}]}],
            "cache_keys": ["k1"]}
    md = render("SELFTEST", "{%x%}", "{%y%}", data)
    assert "| добрый | 44.04 ipm (кат. 3, скорее низкая) | слово | amod_S_A #4, 8.57 | 137 | 5 |" in md, md
    assert "Advisory" in md and "`k1`" in md
    print("nkrya_evidence_card selftest OK (3 checks, offline)")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--id")
    ap.add_argument("--german", default="")
    ap.add_argument("--current", default="")
    ap.add_argument("--heads")
    ap.add_argument("--candidates")
    ap.add_argument("--out")
    ap.add_argument("--json-out")
    ap.add_argument("--offline", action="store_true")
    a = ap.parse_args(argv)
    if a.selftest:
        selftest()
        return 0
    if not (a.id and a.heads and a.candidates):
        ap.error("--id, --heads and --candidates are required")
    cli = nk.NkryaClient(offline=a.offline)
    try:
        data = gather(cli, parse_items(a.heads), parse_items(a.candidates))
    except nk.NkryaError as e:
        print("NKRYa: %s" % e, file=sys.stderr)
        return 2
    md = render(a.id, a.german, a.current, data)
    if a.out:
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(md)
    else:
        print(md)
    if a.json_out:
        with open(a.json_out, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=1)
            f.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
